
package org.sepro.teacherweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CvteacherServicews", targetNamespace = "http://serviceimpl.teacherweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/CvteacherServicews/CvteacherServicewsImpl?wsdl")
public class CvteacherServicews
    extends Service
{

    private final static URL CVTEACHERSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException CVTEACHERSERVICEWS_EXCEPTION;
    private final static QName CVTEACHERSERVICEWS_QNAME = new QName("http://serviceimpl.teacherweb.sepro.org/", "CvteacherServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/CvteacherServicews/CvteacherServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CVTEACHERSERVICEWS_WSDL_LOCATION = url;
        CVTEACHERSERVICEWS_EXCEPTION = e;
    }

    public CvteacherServicews() {
        super(__getWsdlLocation(), CVTEACHERSERVICEWS_QNAME);
    }

    public CvteacherServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), CVTEACHERSERVICEWS_QNAME, features);
    }

    public CvteacherServicews(URL wsdlLocation) {
        super(wsdlLocation, CVTEACHERSERVICEWS_QNAME);
    }

    public CvteacherServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CVTEACHERSERVICEWS_QNAME, features);
    }

    public CvteacherServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CvteacherServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CvteacherServicewsEndpoint
     */
    @WebEndpoint(name = "CvteacherServicewsImplPort")
    public CvteacherServicewsEndpoint getCvteacherServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.teacherweb.sepro.org/", "CvteacherServicewsImplPort"), CvteacherServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CvteacherServicewsEndpoint
     */
    @WebEndpoint(name = "CvteacherServicewsImplPort")
    public CvteacherServicewsEndpoint getCvteacherServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.teacherweb.sepro.org/", "CvteacherServicewsImplPort"), CvteacherServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CVTEACHERSERVICEWS_EXCEPTION!= null) {
            throw CVTEACHERSERVICEWS_EXCEPTION;
        }
        return CVTEACHERSERVICEWS_WSDL_LOCATION;
    }

}
