
package org.sepro.teacherweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.teacherweb.serviceapi.DetailteacherDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DetailteacherServicewsEndpoint", targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.teacherweb.serviceapi.ObjectFactoryDetailTeacher.class
})
public interface DetailteacherServicewsEndpoint {


    /**
     * 
     * @param detailteacherDto
     * @return
     *     returns org.sepro.teacherweb.serviceapi.DetailteacherDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
    @RequestWrapper(localName = "createDetailteacherServicews", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.CreateDetailteacherServicews")
    @ResponseWrapper(localName = "createDetailteacherServicewsResponse", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.CreateDetailteacherServicewsResponse")
    public DetailteacherDto createDetailteacherServicews(
        @WebParam(name = "detailteacherDto", targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
        DetailteacherDto detailteacherDto);

    /**
     * 
     * @param detailteacherDto
     * @return
     *     returns java.util.List<org.sepro.teacherweb.serviceapi.DetailteacherDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
    @RequestWrapper(localName = "searchDetailteacherServicews", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.SearchDetailteacherServicews")
    @ResponseWrapper(localName = "searchDetailteacherServicewsResponse", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.SearchDetailteacherServicewsResponse")
    public List<DetailteacherDto> searchDetailteacherServicews(
        @WebParam(name = "detailteacherDto", targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
        DetailteacherDto detailteacherDto);

    /**
     * 
     * @param detailteacherDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDetailteacherServicews", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.DeleteDetailteacherServicews")
    @ResponseWrapper(localName = "deleteDetailteacherServicewsResponse", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.DeleteDetailteacherServicewsResponse")
    public void deleteDetailteacherServicews(
        @WebParam(name = "detailteacherDto", targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
        DetailteacherDto detailteacherDto);

    /**
     * 
     * @param detailteacherDto
     * @return
     *     returns org.sepro.teacherweb.serviceapi.DetailteacherDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
    @RequestWrapper(localName = "updateDetailteacherServicews", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.UpdateDetailteacherServicews")
    @ResponseWrapper(localName = "updateDetailteacherServicewsResponse", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.UpdateDetailteacherServicewsResponse")
    public DetailteacherDto updateDetailteacherServicews(
        @WebParam(name = "detailteacherDto", targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
        DetailteacherDto detailteacherDto);

}
