
package org.sepro.teacherweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DetailteacherServicews", targetNamespace = "http://serviceimpl.teacherweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/DetailteacherServicews/DetailteacherServicewsImpl?wsdl")
public class DetailteacherServicews
    extends Service
{

    private final static URL DETAILTEACHERSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException DETAILTEACHERSERVICEWS_EXCEPTION;
    private final static QName DETAILTEACHERSERVICEWS_QNAME = new QName("http://serviceimpl.teacherweb.sepro.org/", "DetailteacherServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/DetailteacherServicews/DetailteacherServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DETAILTEACHERSERVICEWS_WSDL_LOCATION = url;
        DETAILTEACHERSERVICEWS_EXCEPTION = e;
    }

    public DetailteacherServicews() {
        super(__getWsdlLocation(), DETAILTEACHERSERVICEWS_QNAME);
    }

    public DetailteacherServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), DETAILTEACHERSERVICEWS_QNAME, features);
    }

    public DetailteacherServicews(URL wsdlLocation) {
        super(wsdlLocation, DETAILTEACHERSERVICEWS_QNAME);
    }

    public DetailteacherServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DETAILTEACHERSERVICEWS_QNAME, features);
    }

    public DetailteacherServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DetailteacherServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DetailteacherServicewsEndpoint
     */
    @WebEndpoint(name = "DetailteacherServicewsImplPort")
    public DetailteacherServicewsEndpoint getDetailteacherServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.teacherweb.sepro.org/", "DetailteacherServicewsImplPort"), DetailteacherServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DetailteacherServicewsEndpoint
     */
    @WebEndpoint(name = "DetailteacherServicewsImplPort")
    public DetailteacherServicewsEndpoint getDetailteacherServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.teacherweb.sepro.org/", "DetailteacherServicewsImplPort"), DetailteacherServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DETAILTEACHERSERVICEWS_EXCEPTION!= null) {
            throw DETAILTEACHERSERVICEWS_EXCEPTION;
        }
        return DETAILTEACHERSERVICEWS_WSDL_LOCATION;
    }

}
