
package org.sepro.teacherweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.teacherweb.serviceapi.IdentityTeacherDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IdentityTeacherServicewsEndpoint", targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
@XmlSeeAlso({org.sepro.teacherweb.serviceapi.ObjectFactoryIdentityTeacher.class
})
public interface IdentityTeacherServicewsEndpoint {


    /**
     * 
     * @param identityTeacherDto
     * @return
     *     returns java.util.List<org.sepro.teacherweb.serviceapi.IdentityTeacherDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
    @RequestWrapper(localName = "searchIdentityTeacherServicews", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.SearchIdentityTeacherServicews")
    @ResponseWrapper(localName = "searchIdentityTeacherServicewsResponse", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.SearchIdentityTeacherServicewsResponse")
    public List<IdentityTeacherDto> searchIdentityTeacherServicews(
        @WebParam(name = "identityTeacherDto", targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
        IdentityTeacherDto identityTeacherDto);

    /**
     * 
     * @param identityTeacherDto
     * @return
     *     returns org.sepro.teacherweb.serviceapi.IdentityTeacherDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
    @RequestWrapper(localName = "createIdentityTeacherServicews", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.CreateIdentityTeacherServicews")
    @ResponseWrapper(localName = "createIdentityTeacherServicewsResponse", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.CreateIdentityTeacherServicewsResponse")
    public IdentityTeacherDto createIdentityTeacherServicews(
        @WebParam(name = "identityTeacherDto", targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
        IdentityTeacherDto identityTeacherDto);

    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.teacherweb.serviceapi.IdentityTeacherDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
    @RequestWrapper(localName = "getAllIdentityTeacherServicews", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.GetAllIdentityTeacherServicews")
    @ResponseWrapper(localName = "getAllIdentityTeacherServicewsResponse", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.GetAllIdentityTeacherServicewsResponse")
    public List<IdentityTeacherDto> getAllIdentityTeacherServicews();

    /**
     * 
     * @param identityTeacherDto
     * @return
     *     returns org.sepro.teacherweb.serviceapi.IdentityTeacherDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
    @RequestWrapper(localName = "updateIdentityTeacherServicews", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.UpdateIdentityTeacherServicews")
    @ResponseWrapper(localName = "updateIdentityTeacherServicewsResponse", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.UpdateIdentityTeacherServicewsResponse")
    public IdentityTeacherDto updateIdentityTeacherServicews(
        @WebParam(name = "identityTeacherDto", targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
        IdentityTeacherDto identityTeacherDto);

    /**
     * 
     * @param identityTeacherDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteIdentityTeacherServicews", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.DeleteIdentityTeacherServicews")
    @ResponseWrapper(localName = "deleteIdentityTeacherServicewsResponse", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.DeleteIdentityTeacherServicewsResponse")
    public void deleteIdentityTeacherServicews(
        @WebParam(name = "identityTeacherDto", targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
        IdentityTeacherDto identityTeacherDto);

}
