
package org.sepro.teacherweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.teacherweb.serviceapi.TeacherModuleDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TeachedModuleServicewsEndpoint", targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.teacherweb.serviceapi.ObjectFactoryTeachedModule.class
})
public interface TeachedModuleServicewsEndpoint {


    /**
     * 
     * @param teacherModuleDto
     * @return
     *     returns java.util.List<org.sepro.teacherweb.serviceapi.TeacherModuleDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
    @RequestWrapper(localName = "searchTeachedModuleServicews", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.SearchTeachedModuleServicews")
    @ResponseWrapper(localName = "searchTeachedModuleServicewsResponse", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.SearchTeachedModuleServicewsResponse")
    public List<TeacherModuleDto> searchTeachedModuleServicews(
        @WebParam(name = "teacherModuleDto", targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
        TeacherModuleDto teacherModuleDto);

    /**
     * 
     * @param teacherModuleDto
     * @return
     *     returns org.sepro.teacherweb.serviceapi.TeacherModuleDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
    @RequestWrapper(localName = "createTeachedModuleServicews", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.CreateTeachedModuleServicews")
    @ResponseWrapper(localName = "createTeachedModuleServicewsResponse", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.CreateTeachedModuleServicewsResponse")
    public TeacherModuleDto createTeachedModuleServicews(
        @WebParam(name = "teacherModuleDto", targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
        TeacherModuleDto teacherModuleDto);

    /**
     * 
     * @param teacherModuleDto
     * @return
     *     returns org.sepro.teacherweb.serviceapi.TeacherModuleDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
    @RequestWrapper(localName = "updateTeachedModuleServicews", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.UpdateTeachedModuleServicews")
    @ResponseWrapper(localName = "updateTeachedModuleServicewsResponse", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.UpdateTeachedModuleServicewsResponse")
    public TeacherModuleDto updateTeachedModuleServicews(
        @WebParam(name = "teacherModuleDto", targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
        TeacherModuleDto teacherModuleDto);

    /**
     * 
     * @param teacherModuleDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteTeachedModuleServicews", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.DeleteTeachedModuleServicews")
    @ResponseWrapper(localName = "deleteTeachedModuleServicewsResponse", targetNamespace = "http://serviceapi.teacherweb.sepro.org/", className = "org.sepro.teacherweb.serviceapi.DeleteTeachedModuleServicewsResponse")
    public void deleteTeachedModuleServicews(
        @WebParam(name = "teacherModuleDto", targetNamespace = "http://serviceapi.teacherweb.sepro.org/")
        TeacherModuleDto teacherModuleDto);

}
