
package org.sepro.teacherweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TeachedModuleServicews", targetNamespace = "http://serviceimpl.teacherweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/TeachedModuleServicews/TeachedModuleServicewsImpl?wsdl")
public class TeachedModuleServicews
    extends Service
{

    private final static URL TEACHEDMODULESERVICEWS_WSDL_LOCATION;
    private final static WebServiceException TEACHEDMODULESERVICEWS_EXCEPTION;
    private final static QName TEACHEDMODULESERVICEWS_QNAME = new QName("http://serviceimpl.teacherweb.sepro.org/", "TeachedModuleServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/TeachedModuleServicews/TeachedModuleServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TEACHEDMODULESERVICEWS_WSDL_LOCATION = url;
        TEACHEDMODULESERVICEWS_EXCEPTION = e;
    }

    public TeachedModuleServicews() {
        super(__getWsdlLocation(), TEACHEDMODULESERVICEWS_QNAME);
    }

    public TeachedModuleServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEACHEDMODULESERVICEWS_QNAME, features);
    }

    public TeachedModuleServicews(URL wsdlLocation) {
        super(wsdlLocation, TEACHEDMODULESERVICEWS_QNAME);
    }

    public TeachedModuleServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEACHEDMODULESERVICEWS_QNAME, features);
    }

    public TeachedModuleServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TeachedModuleServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TeachedModuleServicewsEndpoint
     */
    @WebEndpoint(name = "TeachedModuleServicewsImplPort")
    public TeachedModuleServicewsEndpoint getTeachedModuleServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.teacherweb.sepro.org/", "TeachedModuleServicewsImplPort"), TeachedModuleServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TeachedModuleServicewsEndpoint
     */
    @WebEndpoint(name = "TeachedModuleServicewsImplPort")
    public TeachedModuleServicewsEndpoint getTeachedModuleServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.teacherweb.sepro.org/", "TeachedModuleServicewsImplPort"), TeachedModuleServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEACHEDMODULESERVICEWS_EXCEPTION!= null) {
            throw TEACHEDMODULESERVICEWS_EXCEPTION;
        }
        return TEACHEDMODULESERVICEWS_WSDL_LOCATION;
    }

}
