
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.parameterweb.serviceapi.PopuplistDto;
import org.sepro.studentweb.serviceapi.ActivitiesDto;
import org.sepro.studentweb.serviceapi.ClasseProgrammDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ActivitiesServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.studentweb.serviceapi.ObjectFactoryActivities.class
})
public interface ActivitiesServicewsEndpoint {


    /**
     * 
     * @param academicYear
     * @param classeProgrammDto
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.ActivitiesDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "searchActivitiesServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchActivitiesServicews")
    @ResponseWrapper(localName = "searchActivitiesServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchActivitiesServicewsResponse")
    public List<ActivitiesDto> searchActivitiesServicews(
        @WebParam(name = "academic_year", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        PopuplistDto academicYear,
        @WebParam(name = "classeProgrammDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ClasseProgrammDto classeProgrammDto);

}
