
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.studentweb.serviceapi.ClassPaymentDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClassPaymentServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.studentweb.serviceapi.ObjectFactoryClassPayment.class
})
public interface ClassPaymentServicewsEndpoint {


    /**
     * 
     * @param classPaymentDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.ClassPaymentDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "createClassPaymentServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateClassPaymentServicews")
    @ResponseWrapper(localName = "createClassPaymentServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateClassPaymentServicewsResponse")
    public ClassPaymentDto createClassPaymentServicews(
        @WebParam(name = "classPaymentDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ClassPaymentDto classPaymentDto);

    /**
     * 
     * @param classPaymentDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteClassPaymentServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteClassPaymentServicews")
    @ResponseWrapper(localName = "deleteClassPaymentServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteClassPaymentServicewsResponse")
    public void deleteClassPaymentServicews(
        @WebParam(name = "classPaymentDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ClassPaymentDto classPaymentDto);

    /**
     * 
     * @param classPaymentDto
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.ClassPaymentDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "searchClassPaymentServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchClassPaymentServicews")
    @ResponseWrapper(localName = "searchClassPaymentServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchClassPaymentServicewsResponse")
    public List<ClassPaymentDto> searchClassPaymentServicews(
        @WebParam(name = "classPaymentDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ClassPaymentDto classPaymentDto);

    /**
     * 
     * @param classPaymentDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.ClassPaymentDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "updateClassPaymentServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateClassPaymentServicews")
    @ResponseWrapper(localName = "updateClassPaymentServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateClassPaymentServicewsResponse")
    public ClassPaymentDto updateClassPaymentServicews(
        @WebParam(name = "classPaymentDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ClassPaymentDto classPaymentDto);

}
