
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.studentweb.serviceapi.ClasseProgrammDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClasseProgrammServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.studentweb.serviceapi.ObjectFactoryClasseProgramm.class
})
public interface ClasseProgrammServicewsEndpoint {


    /**
     * 
     * @param classeProgrammDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.ClasseProgrammDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "updateClasseProgrammServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateClasseProgrammServicews")
    @ResponseWrapper(localName = "updateClasseProgrammServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateClasseProgrammServicewsResponse")
    public ClasseProgrammDto updateClasseProgrammServicews(
        @WebParam(name = "classeProgrammDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ClasseProgrammDto classeProgrammDto);

    /**
     * 
     * @param classeProgrammDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.ClasseProgrammDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "createClasseProgrammServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateClasseProgrammServicews")
    @ResponseWrapper(localName = "createClasseProgrammServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateClasseProgrammServicewsResponse")
    public ClasseProgrammDto createClasseProgrammServicews(
        @WebParam(name = "classeProgrammDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ClasseProgrammDto classeProgrammDto);

    /**
     * 
     * @param classeProgrammDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteClasseProgrammServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteClasseProgrammServicews")
    @ResponseWrapper(localName = "deleteClasseProgrammServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteClasseProgrammServicewsResponse")
    public void deleteClasseProgrammServicews(
        @WebParam(name = "classeProgrammDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ClasseProgrammDto classeProgrammDto);

    /**
     * 
     * @param classeProgrammDto
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.ClasseProgrammDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "searchClasseProgrammServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchClasseProgrammServicews")
    @ResponseWrapper(localName = "searchClasseProgrammServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchClasseProgrammServicewsResponse")
    public List<ClasseProgrammDto> searchClasseProgrammServicews(
        @WebParam(name = "classeProgrammDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ClasseProgrammDto classeProgrammDto);

}
