
package org.sepro.studentweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClasseProgrammServicews", targetNamespace = "http://serviceimpl.studentweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ClasseProgrammServicews/ClasseProgrammServicewsImpl?wsdl")
public class ClasseProgrammServicews
    extends Service
{

    private final static URL CLASSEPROGRAMMSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException CLASSEPROGRAMMSERVICEWS_EXCEPTION;
    private final static QName CLASSEPROGRAMMSERVICEWS_QNAME = new QName("http://serviceimpl.studentweb.sepro.org/", "ClasseProgrammServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ClasseProgrammServicews/ClasseProgrammServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLASSEPROGRAMMSERVICEWS_WSDL_LOCATION = url;
        CLASSEPROGRAMMSERVICEWS_EXCEPTION = e;
    }

    public ClasseProgrammServicews() {
        super(__getWsdlLocation(), CLASSEPROGRAMMSERVICEWS_QNAME);
    }

    public ClasseProgrammServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLASSEPROGRAMMSERVICEWS_QNAME, features);
    }

    public ClasseProgrammServicews(URL wsdlLocation) {
        super(wsdlLocation, CLASSEPROGRAMMSERVICEWS_QNAME);
    }

    public ClasseProgrammServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLASSEPROGRAMMSERVICEWS_QNAME, features);
    }

    public ClasseProgrammServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClasseProgrammServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClasseProgrammServicewsEndpoint
     */
    @WebEndpoint(name = "ClasseProgrammServicewsImplPort")
    public ClasseProgrammServicewsEndpoint getClasseProgrammServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "ClasseProgrammServicewsImplPort"), ClasseProgrammServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClasseProgrammServicewsEndpoint
     */
    @WebEndpoint(name = "ClasseProgrammServicewsImplPort")
    public ClasseProgrammServicewsEndpoint getClasseProgrammServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "ClasseProgrammServicewsImplPort"), ClasseProgrammServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLASSEPROGRAMMSERVICEWS_EXCEPTION!= null) {
            throw CLASSEPROGRAMMSERVICEWS_EXCEPTION;
        }
        return CLASSEPROGRAMMSERVICEWS_WSDL_LOCATION;
    }

}
