
package org.sepro.studentweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClassPaymentServicews", targetNamespace = "http://serviceimpl.studentweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ClassPaymentServicews/ClassPaymentServicewsImpl?wsdl")
public class ClassPaymentServicews
    extends Service
{

    private final static URL CLASSPAYMENTSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException CLASSPAYMENTSERVICEWS_EXCEPTION;
    private final static QName CLASSPAYMENTSERVICEWS_QNAME = new QName("http://serviceimpl.studentweb.sepro.org/", "ClassPaymentServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ClassPaymentServicews/ClassPaymentServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLASSPAYMENTSERVICEWS_WSDL_LOCATION = url;
        CLASSPAYMENTSERVICEWS_EXCEPTION = e;
    }

    public ClassPaymentServicews() {
        super(__getWsdlLocation(), CLASSPAYMENTSERVICEWS_QNAME);
    }

    public ClassPaymentServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLASSPAYMENTSERVICEWS_QNAME, features);
    }

    public ClassPaymentServicews(URL wsdlLocation) {
        super(wsdlLocation, CLASSPAYMENTSERVICEWS_QNAME);
    }

    public ClassPaymentServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLASSPAYMENTSERVICEWS_QNAME, features);
    }

    public ClassPaymentServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClassPaymentServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClassPaymentServicewsEndpoint
     */
    @WebEndpoint(name = "ClassPaymentServicewsImplPort")
    public ClassPaymentServicewsEndpoint getClassPaymentServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "ClassPaymentServicewsImplPort"), ClassPaymentServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClassPaymentServicewsEndpoint
     */
    @WebEndpoint(name = "ClassPaymentServicewsImplPort")
    public ClassPaymentServicewsEndpoint getClassPaymentServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "ClassPaymentServicewsImplPort"), ClassPaymentServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLASSPAYMENTSERVICEWS_EXCEPTION!= null) {
            throw CLASSPAYMENTSERVICEWS_EXCEPTION;
        }
        return CLASSPAYMENTSERVICEWS_WSDL_LOCATION;
    }

}
