
package org.sepro.studentweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EventsForumServicews", targetNamespace = "http://serviceimpl.studentweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/EventsForumServicews/EventsForumServicewsImpl?wsdl")
public class EventsForumServicews
    extends Service
{

    private final static URL EVENTSFORUMSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException EVENTSFORUMSERVICEWS_EXCEPTION;
    private final static QName EVENTSFORUMSERVICEWS_QNAME = new QName("http://serviceimpl.studentweb.sepro.org/", "EventsForumServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/EventsForumServicews/EventsForumServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EVENTSFORUMSERVICEWS_WSDL_LOCATION = url;
        EVENTSFORUMSERVICEWS_EXCEPTION = e;
    }

    public EventsForumServicews() {
        super(__getWsdlLocation(), EVENTSFORUMSERVICEWS_QNAME);
    }

    public EventsForumServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), EVENTSFORUMSERVICEWS_QNAME, features);
    }

    public EventsForumServicews(URL wsdlLocation) {
        super(wsdlLocation, EVENTSFORUMSERVICEWS_QNAME);
    }

    public EventsForumServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EVENTSFORUMSERVICEWS_QNAME, features);
    }

    public EventsForumServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EventsForumServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EventsForumServicewsEndpoint
     */
    @WebEndpoint(name = "EventsForumServicewsImplPort")
    public EventsForumServicewsEndpoint getEventsForumServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "EventsForumServicewsImplPort"), EventsForumServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EventsForumServicewsEndpoint
     */
    @WebEndpoint(name = "EventsForumServicewsImplPort")
    public EventsForumServicewsEndpoint getEventsForumServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "EventsForumServicewsImplPort"), EventsForumServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EVENTSFORUMSERVICEWS_EXCEPTION!= null) {
            throw EVENTSFORUMSERVICEWS_EXCEPTION;
        }
        return EVENTSFORUMSERVICEWS_WSDL_LOCATION;
    }

}
