
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.studentweb.serviceapi.EventsForumDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EventsForumServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.studentweb.serviceapi.ObjectFactoryEventsForum.class
})
public interface EventsForumServicewsEndpoint {


    /**
     * 
     * @param eventsForumDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.EventsForumDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "updateEventsForumServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateEventsForumServicews")
    @ResponseWrapper(localName = "updateEventsForumServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateEventsForumServicewsResponse")
    public EventsForumDto updateEventsForumServicews(
        @WebParam(name = "eventsForumDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        EventsForumDto eventsForumDto);

    /**
     * 
     * @param eventsForumDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.EventsForumDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "createEventsForumServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateEventsForumServicews")
    @ResponseWrapper(localName = "createEventsForumServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateEventsForumServicewsResponse")
    public EventsForumDto createEventsForumServicews(
        @WebParam(name = "eventsForumDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        EventsForumDto eventsForumDto);

    /**
     * 
     * @param eventsForumDto
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.EventsForumDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "searchEventsForumServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchEventsForumServicews")
    @ResponseWrapper(localName = "searchEventsForumServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchEventsForumServicewsResponse")
    public List<EventsForumDto> searchEventsForumServicews(
        @WebParam(name = "eventsForumDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        EventsForumDto eventsForumDto);

    /**
     * 
     * @param eventsForumDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteEventsForumServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteEventsForumServicews")
    @ResponseWrapper(localName = "deleteEventsForumServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteEventsForumServicewsResponse")
    public void deleteEventsForumServicews(
        @WebParam(name = "eventsForumDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        EventsForumDto eventsForumDto);

}
