
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.studentweb.serviceapi.EventsStatusDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EventsStatusServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.studentweb.serviceapi.ObjectFactoryEventsStatus.class
})
public interface EventsStatusServicewsEndpoint {


    /**
     * 
     * @param eventsStatusDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.EventsStatusDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "updateEventsStatusServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateEventsStatusServicews")
    @ResponseWrapper(localName = "updateEventsStatusServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateEventsStatusServicewsResponse")
    public EventsStatusDto updateEventsStatusServicews(
        @WebParam(name = "eventsStatusDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        EventsStatusDto eventsStatusDto);

    /**
     * 
     * @param eventsStatusDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.EventsStatusDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "createEventsStatusServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateEventsStatusServicews")
    @ResponseWrapper(localName = "createEventsStatusServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateEventsStatusServicewsResponse")
    public EventsStatusDto createEventsStatusServicews(
        @WebParam(name = "eventsStatusDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        EventsStatusDto eventsStatusDto);

    /**
     * 
     * @param eventsStatusDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteEventsStatusServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteEventsStatusServicews")
    @ResponseWrapper(localName = "deleteEventsStatusServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteEventsStatusServicewsResponse")
    public void deleteEventsStatusServicews(
        @WebParam(name = "eventsStatusDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        EventsStatusDto eventsStatusDto);

    /**
     * 
     * @param eventsStatusDto
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.EventsStatusDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "searchEventsStatusServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchEventsStatusServicews")
    @ResponseWrapper(localName = "searchEventsStatusServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchEventsStatusServicewsResponse")
    public List<EventsStatusDto> searchEventsStatusServicews(
        @WebParam(name = "eventsStatusDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        EventsStatusDto eventsStatusDto);

}
