
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.studentweb.serviceapi.ExamGroupDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExamGroupServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
   
    org.sepro.studentweb.serviceapi.ObjectFactoryExamGroup.class
    
})
public interface ExamGroupServicewsEndpoint {


    /**
     * 
     * @param examGroupDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteExamGroupServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteExamGroupServicews")
    @ResponseWrapper(localName = "deleteExamGroupServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteExamGroupServicewsResponse")
    public void deleteExamGroupServicews(
        @WebParam(name = "examGroupDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ExamGroupDto examGroupDto);

    /**
     * 
     * @param examGroupDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.ExamGroupDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "updateExamGroupServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateExamGroupServicews")
    @ResponseWrapper(localName = "updateExamGroupServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateExamGroupServicewsResponse")
    public ExamGroupDto updateExamGroupServicews(
        @WebParam(name = "examGroupDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ExamGroupDto examGroupDto);

    /**
     * 
     * @param examGroupDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.ExamGroupDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "createExamGroupServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateExamGroupServicews")
    @ResponseWrapper(localName = "createExamGroupServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateExamGroupServicewsResponse")
    public ExamGroupDto createExamGroupServicews(
        @WebParam(name = "examGroupDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ExamGroupDto examGroupDto);

    /**
     * 
     * @param examGroupDto
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.ExamGroupDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "searchExamGroupServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchExamGroupServicews")
    @ResponseWrapper(localName = "searchExamGroupServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchExamGroupServicewsResponse")
    public List<ExamGroupDto> searchExamGroupServicews(
        @WebParam(name = "examGroupDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ExamGroupDto examGroupDto);

}
