
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.studentweb.serviceapi.ExamDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExamServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.studentweb.serviceapi.ObjectFactoryExam.class
})
public interface ExamServicewsEndpoint {


    /**
     * 
     * @param examDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.ExamDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "updateExamServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateExamServicews")
    @ResponseWrapper(localName = "updateExamServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateExamServicewsResponse")
    public ExamDto updateExamServicews(
        @WebParam(name = "examDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ExamDto examDto);

    /**
     * 
     * @param examDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteExamServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteExamServicews")
    @ResponseWrapper(localName = "deleteExamServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteExamServicewsResponse")
    public void deleteExamServicews(
        @WebParam(name = "examDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ExamDto examDto);

    /**
     * 
     * @param examDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.ExamDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "createExamServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateExamServicews")
    @ResponseWrapper(localName = "createExamServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateExamServicewsResponse")
    public ExamDto createExamServicews(
        @WebParam(name = "examDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ExamDto examDto);

    /**
     * 
     * @param examDto
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.ExamDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "searchExamServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchExamServicews")
    @ResponseWrapper(localName = "searchExamServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchExamServicewsResponse")
    public List<ExamDto> searchExamServicews(
        @WebParam(name = "examDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ExamDto examDto);

}
