
package org.sepro.studentweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExamGroupServicews", targetNamespace = "http://serviceimpl.studentweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ExamGroupServicews/ExamGroupServicewsImpl?wsdl")
public class ExamGroupServicews
    extends Service
{

    private final static URL EXAMGROUPSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException EXAMGROUPSERVICEWS_EXCEPTION;
    private final static QName EXAMGROUPSERVICEWS_QNAME = new QName("http://serviceimpl.studentweb.sepro.org/", "ExamGroupServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ExamGroupServicews/ExamGroupServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXAMGROUPSERVICEWS_WSDL_LOCATION = url;
        EXAMGROUPSERVICEWS_EXCEPTION = e;
    }

    public ExamGroupServicews() {
        super(__getWsdlLocation(), EXAMGROUPSERVICEWS_QNAME);
    }

    public ExamGroupServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXAMGROUPSERVICEWS_QNAME, features);
    }

    public ExamGroupServicews(URL wsdlLocation) {
        super(wsdlLocation, EXAMGROUPSERVICEWS_QNAME);
    }

    public ExamGroupServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXAMGROUPSERVICEWS_QNAME, features);
    }

    public ExamGroupServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExamGroupServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExamGroupServicewsEndpoint
     */
    @WebEndpoint(name = "ExamGroupServicewsImplPort")
    public ExamGroupServicewsEndpoint getExamGroupServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "ExamGroupServicewsImplPort"), ExamGroupServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExamGroupServicewsEndpoint
     */
    @WebEndpoint(name = "ExamGroupServicewsImplPort")
    public ExamGroupServicewsEndpoint getExamGroupServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "ExamGroupServicewsImplPort"), ExamGroupServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXAMGROUPSERVICEWS_EXCEPTION!= null) {
            throw EXAMGROUPSERVICEWS_EXCEPTION;
        }
        return EXAMGROUPSERVICEWS_WSDL_LOCATION;
    }

}
