
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.studentweb.serviceapi.ExamModuleGroupDto;
import org.sepro.studentweb.serviceapi.ObjectFactoryExamModuleGroup;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExamModuleGroupServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactoryExamModuleGroup.class
})
public interface ExamModuleGroupServicewsEndpoint {


    /**
     * 
     * @param examModuleGroupDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.ExamModuleGroupDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "createExamModuleGroupServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateExamModuleGroupServicews")
    @ResponseWrapper(localName = "createExamModuleGroupServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateExamModuleGroupServicewsResponse")
    public ExamModuleGroupDto createExamModuleGroupServicews(
        @WebParam(name = "examModuleGroupDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ExamModuleGroupDto examModuleGroupDto);

    /**
     * 
     * @param examModuleGroupDto
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.ExamModuleGroupDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "searchExamModuleGroupServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchExamModuleGroupServicews")
    @ResponseWrapper(localName = "searchExamModuleGroupServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchExamModuleGroupServicewsResponse")
    public List<ExamModuleGroupDto> searchExamModuleGroupServicews(
        @WebParam(name = "examModuleGroupDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ExamModuleGroupDto examModuleGroupDto);

    /**
     * 
     * @param examModuleGroupDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteExamModuleGroupServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteExamModuleGroupServicews")
    @ResponseWrapper(localName = "deleteExamModuleGroupServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteExamModuleGroupServicewsResponse")
    public void deleteExamModuleGroupServicews(
        @WebParam(name = "examModuleGroupDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ExamModuleGroupDto examModuleGroupDto);

    /**
     * 
     * @param examModuleGroupDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.ExamModuleGroupDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "updateExamModuleGroupServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateExamModuleGroupServicews")
    @ResponseWrapper(localName = "updateExamModuleGroupServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateExamModuleGroupServicewsResponse")
    public ExamModuleGroupDto updateExamModuleGroupServicews(
        @WebParam(name = "examModuleGroupDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ExamModuleGroupDto examModuleGroupDto);

}
