
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.studentweb.serviceapi.ModuleAcademiExamDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ModuleAcademiExamServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.studentweb.serviceapi.ObjectFactoryModuleAcademiExam.class
})
public interface ModuleAcademiExamServicewsEndpoint {


    /**
     * 
     * @param moduleAcademiExamDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteModuleAcademiExamServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteModuleAcademiExamServicews")
    @ResponseWrapper(localName = "deleteModuleAcademiExamServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteModuleAcademiExamServicewsResponse")
    public void deleteModuleAcademiExamServicews(
        @WebParam(name = "moduleAcademiExamDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ModuleAcademiExamDto moduleAcademiExamDto);

    /**
     * 
     * @param moduleAcademiExamDto
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.ModuleAcademiExamDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "searchModuleAcademiExamServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchModuleAcademiExamServicews")
    @ResponseWrapper(localName = "searchModuleAcademiExamServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchModuleAcademiExamServicewsResponse")
    public List<ModuleAcademiExamDto> searchModuleAcademiExamServicews(
        @WebParam(name = "moduleAcademiExamDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ModuleAcademiExamDto moduleAcademiExamDto);

    /**
     * 
     * @param moduleAcademiExamDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.ModuleAcademiExamDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "createModuleAcademiExamServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateModuleAcademiExamServicews")
    @ResponseWrapper(localName = "createModuleAcademiExamServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateModuleAcademiExamServicewsResponse")
    public ModuleAcademiExamDto createModuleAcademiExamServicews(
        @WebParam(name = "moduleAcademiExamDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ModuleAcademiExamDto moduleAcademiExamDto);

    /**
     * 
     * @param moduleAcademiExamDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.ModuleAcademiExamDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "updateModuleAcademiExamServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateModuleAcademiExamServicews")
    @ResponseWrapper(localName = "updateModuleAcademiExamServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateModuleAcademiExamServicewsResponse")
    public ModuleAcademiExamDto updateModuleAcademiExamServicews(
        @WebParam(name = "moduleAcademiExamDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        ModuleAcademiExamDto moduleAcademiExamDto);

}
