
package org.sepro.studentweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ModuleAcademiExamServicews", targetNamespace = "http://serviceimpl.studentweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ModuleAcademiExamServicews/ModuleAcademiExamServicewsImpl?wsdl")
public class ModuleAcademiExamServicews
    extends Service
{

    private final static URL MODULEACADEMIEXAMSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException MODULEACADEMIEXAMSERVICEWS_EXCEPTION;
    private final static QName MODULEACADEMIEXAMSERVICEWS_QNAME = new QName("http://serviceimpl.studentweb.sepro.org/", "ModuleAcademiExamServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ModuleAcademiExamServicews/ModuleAcademiExamServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODULEACADEMIEXAMSERVICEWS_WSDL_LOCATION = url;
        MODULEACADEMIEXAMSERVICEWS_EXCEPTION = e;
    }

    public ModuleAcademiExamServicews() {
        super(__getWsdlLocation(), MODULEACADEMIEXAMSERVICEWS_QNAME);
    }

    public ModuleAcademiExamServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODULEACADEMIEXAMSERVICEWS_QNAME, features);
    }

    public ModuleAcademiExamServicews(URL wsdlLocation) {
        super(wsdlLocation, MODULEACADEMIEXAMSERVICEWS_QNAME);
    }

    public ModuleAcademiExamServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODULEACADEMIEXAMSERVICEWS_QNAME, features);
    }

    public ModuleAcademiExamServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModuleAcademiExamServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModuleAcademiExamServicewsEndpoint
     */
    @WebEndpoint(name = "ModuleAcademiExamServicewsImplPort")
    public ModuleAcademiExamServicewsEndpoint getModuleAcademiExamServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "ModuleAcademiExamServicewsImplPort"), ModuleAcademiExamServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModuleAcademiExamServicewsEndpoint
     */
    @WebEndpoint(name = "ModuleAcademiExamServicewsImplPort")
    public ModuleAcademiExamServicewsEndpoint getModuleAcademiExamServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "ModuleAcademiExamServicewsImplPort"), ModuleAcademiExamServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODULEACADEMIEXAMSERVICEWS_EXCEPTION!= null) {
            throw MODULEACADEMIEXAMSERVICEWS_EXCEPTION;
        }
        return MODULEACADEMIEXAMSERVICEWS_WSDL_LOCATION;
    }

}
