
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.studentweb.serviceapi.StudentCVDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentCVServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
    
    org.sepro.studentweb.serviceapi.ObjectFactoryStudentCV.class
})
public interface StudentCVServicewsEndpoint {


    /**
     * 
     * @param studentCVDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.StudentCVDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "createStudentCVServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateStudentCVServicews")
    @ResponseWrapper(localName = "createStudentCVServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateStudentCVServicewsResponse")
    public StudentCVDto createStudentCVServicews(
        @WebParam(name = "studentCVDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentCVDto studentCVDto);

    /**
     * 
     * @param studentCVDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteStudentCVServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteStudentCVServicews")
    @ResponseWrapper(localName = "deleteStudentCVServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteStudentCVServicewsResponse")
    public void deleteStudentCVServicews(
        @WebParam(name = "studentCVDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentCVDto studentCVDto);

    /**
     * 
     * @param studentCVDto
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.StudentCVDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "searchStudentCVServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentCVServicews")
    @ResponseWrapper(localName = "searchStudentCVServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentCVServicewsResponse")
    public List<StudentCVDto> searchStudentCVServicews(
        @WebParam(name = "studentCVDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentCVDto studentCVDto);

    /**
     * 
     * @param studentCVDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.StudentCVDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "updateStudentCVServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateStudentCVServicews")
    @ResponseWrapper(localName = "updateStudentCVServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateStudentCVServicewsResponse")
    public StudentCVDto updateStudentCVServicews(
        @WebParam(name = "studentCVDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentCVDto studentCVDto);

}
