
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.studentweb.serviceapi.StudentDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
    
    org.sepro.studentweb.serviceapi.ObjectFactoryStudent.class
})
public interface StudentServicewsEndpoint {


    /**
     * 
     * @param studentDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.StudentDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "createStudentServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateStudentServicews")
    @ResponseWrapper(localName = "createStudentServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateStudentServicewsResponse")
    public StudentDto createStudentServicews(
        @WebParam(name = "studentDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentDto studentDto);

    /**
     * 
     * @param studentDto
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.StudentDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "searchStudentServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentServicews")
    @ResponseWrapper(localName = "searchStudentServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentServicewsResponse")
    public List<StudentDto> searchStudentServicews(
        @WebParam(name = "studentDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentDto studentDto);

    /**
     * 
     * @param studentDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.StudentDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "updateStudentServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateStudentServicews")
    @ResponseWrapper(localName = "updateStudentServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateStudentServicewsResponse")
    public StudentDto updateStudentServicews(
        @WebParam(name = "studentDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentDto studentDto);

    /**
     * 
     * @param studentDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteStudentServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteStudentServicews")
    @ResponseWrapper(localName = "deleteStudentServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteStudentServicewsResponse")
    public void deleteStudentServicews(
        @WebParam(name = "studentDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentDto studentDto);

}
