
package org.sepro.studentweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentEventsServicews", targetNamespace = "http://serviceimpl.studentweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/StudentEventsServicews/StudentEventsServicewsImpl?wsdl")
public class StudentEventsServicews
    extends Service
{

    private final static URL STUDENTEVENTSSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException STUDENTEVENTSSERVICEWS_EXCEPTION;
    private final static QName STUDENTEVENTSSERVICEWS_QNAME = new QName("http://serviceimpl.studentweb.sepro.org/", "StudentEventsServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/StudentEventsServicews/StudentEventsServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTEVENTSSERVICEWS_WSDL_LOCATION = url;
        STUDENTEVENTSSERVICEWS_EXCEPTION = e;
    }

    public StudentEventsServicews() {
        super(__getWsdlLocation(), STUDENTEVENTSSERVICEWS_QNAME);
    }

    public StudentEventsServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTEVENTSSERVICEWS_QNAME, features);
    }

    public StudentEventsServicews(URL wsdlLocation) {
        super(wsdlLocation, STUDENTEVENTSSERVICEWS_QNAME);
    }

    public StudentEventsServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTEVENTSSERVICEWS_QNAME, features);
    }

    public StudentEventsServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentEventsServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentEventsServicewsEndpoint
     */
    @WebEndpoint(name = "StudentEventsServicewsImplPort")
    public StudentEventsServicewsEndpoint getStudentEventsServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "StudentEventsServicewsImplPort"), StudentEventsServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentEventsServicewsEndpoint
     */
    @WebEndpoint(name = "StudentEventsServicewsImplPort")
    public StudentEventsServicewsEndpoint getStudentEventsServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "StudentEventsServicewsImplPort"), StudentEventsServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTEVENTSSERVICEWS_EXCEPTION!= null) {
            throw STUDENTEVENTSSERVICEWS_EXCEPTION;
        }
        return STUDENTEVENTSSERVICEWS_WSDL_LOCATION;
    }

}
