
package org.sepro.studentweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentDataDtoServicews", targetNamespace = "http://serviceimpl.studentweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/StudentDataDtoServicews/StudentDataDtoServicewsImpl?wsdl")
public class StudentDataDtoServicews
    extends Service
{

    private final static URL STUDENTDATADTOSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException STUDENTDATADTOSERVICEWS_EXCEPTION;
    private final static QName STUDENTDATADTOSERVICEWS_QNAME = new QName("http://serviceimpl.studentweb.sepro.org/", "StudentDataDtoServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/StudentDataDtoServicews/StudentDataDtoServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTDATADTOSERVICEWS_WSDL_LOCATION = url;
        STUDENTDATADTOSERVICEWS_EXCEPTION = e;
    }

    public StudentDataDtoServicews() {
        super(__getWsdlLocation(), STUDENTDATADTOSERVICEWS_QNAME);
    }

    public StudentDataDtoServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTDATADTOSERVICEWS_QNAME, features);
    }

    public StudentDataDtoServicews(URL wsdlLocation) {
        super(wsdlLocation, STUDENTDATADTOSERVICEWS_QNAME);
    }

    public StudentDataDtoServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTDATADTOSERVICEWS_QNAME, features);
    }

    public StudentDataDtoServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentDataDtoServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentDataDtoServicewsEndpoint
     */
    @WebEndpoint(name = "StudentDataDtoServicewsImplPort")
    public StudentDataDtoServicewsEndpoint getStudentDataDtoServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "StudentDataDtoServicewsImplPort"), StudentDataDtoServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentDataDtoServicewsEndpoint
     */
    @WebEndpoint(name = "StudentDataDtoServicewsImplPort")
    public StudentDataDtoServicewsEndpoint getStudentDataDtoServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "StudentDataDtoServicewsImplPort"), StudentDataDtoServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTDATADTOSERVICEWS_EXCEPTION!= null) {
            throw STUDENTDATADTOSERVICEWS_EXCEPTION;
        }
        return STUDENTDATADTOSERVICEWS_WSDL_LOCATION;
    }

}
