
package org.sepro.studentweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentExamGroupServicews", targetNamespace = "http://serviceimpl.studentweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/StudentExamGroupServicews/StudentExamGroupServicewsImpl?wsdl")
public class StudentExamGroupServicews
    extends Service
{

    private final static URL STUDENTEXAMGROUPSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException STUDENTEXAMGROUPSERVICEWS_EXCEPTION;
    private final static QName STUDENTEXAMGROUPSERVICEWS_QNAME = new QName("http://serviceimpl.studentweb.sepro.org/", "StudentExamGroupServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/StudentExamGroupServicews/StudentExamGroupServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTEXAMGROUPSERVICEWS_WSDL_LOCATION = url;
        STUDENTEXAMGROUPSERVICEWS_EXCEPTION = e;
    }

    public StudentExamGroupServicews() {
        super(__getWsdlLocation(), STUDENTEXAMGROUPSERVICEWS_QNAME);
    }

    public StudentExamGroupServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTEXAMGROUPSERVICEWS_QNAME, features);
    }

    public StudentExamGroupServicews(URL wsdlLocation) {
        super(wsdlLocation, STUDENTEXAMGROUPSERVICEWS_QNAME);
    }

    public StudentExamGroupServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTEXAMGROUPSERVICEWS_QNAME, features);
    }

    public StudentExamGroupServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentExamGroupServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentExamGroupServicewsEndpoint
     */
    @WebEndpoint(name = "StudentExamGroupServicewsImplPort")
    public StudentExamGroupServicewsEndpoint getStudentExamGroupServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "StudentExamGroupServicewsImplPort"), StudentExamGroupServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentExamGroupServicewsEndpoint
     */
    @WebEndpoint(name = "StudentExamGroupServicewsImplPort")
    public StudentExamGroupServicewsEndpoint getStudentExamGroupServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "StudentExamGroupServicewsImplPort"), StudentExamGroupServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTEXAMGROUPSERVICEWS_EXCEPTION!= null) {
            throw STUDENTEXAMGROUPSERVICEWS_EXCEPTION;
        }
        return STUDENTEXAMGROUPSERVICEWS_WSDL_LOCATION;
    }

}
