
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.studentweb.serviceapi.StudentPresenceDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentPresenceServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.studentweb.serviceapi.ObjectFactoryStudentPresence.class
})
public interface StudentPresenceServicewsEndpoint {


    /**
     * 
     * @param studentPresenceDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.StudentPresenceDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "createStudentPresenceServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateStudentPresenceServicews")
    @ResponseWrapper(localName = "createStudentPresenceServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateStudentPresenceServicewsResponse")
    public StudentPresenceDto createStudentPresenceServicews(
        @WebParam(name = "studentPresenceDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentPresenceDto studentPresenceDto);

    /**
     * 
     * @param studentPresenceDto
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.StudentPresenceDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "searchStudentPresenceServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentPresenceServicews")
    @ResponseWrapper(localName = "searchStudentPresenceServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentPresenceServicewsResponse")
    public List<StudentPresenceDto> searchStudentPresenceServicews(
        @WebParam(name = "studentPresenceDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentPresenceDto studentPresenceDto);

    /**
     * 
     * @param studentPresenceDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteStudentPresenceServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteStudentPresenceServicews")
    @ResponseWrapper(localName = "deleteStudentPresenceServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteStudentPresenceServicewsResponse")
    public void deleteStudentPresenceServicews(
        @WebParam(name = "studentPresenceDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentPresenceDto studentPresenceDto);

    /**
     * 
     * @param studentPresenceDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.StudentPresenceDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "updateStudentPresenceServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateStudentPresenceServicews")
    @ResponseWrapper(localName = "updateStudentPresenceServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateStudentPresenceServicewsResponse")
    public StudentPresenceDto updateStudentPresenceServicews(
        @WebParam(name = "studentPresenceDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentPresenceDto studentPresenceDto);

}
