
package org.sepro.studentweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentCVServicews", targetNamespace = "http://serviceimpl.studentweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/StudentCVServicews/StudentCVServicewsImpl?wsdl")
public class StudentCVServicews
    extends Service
{

    private final static URL STUDENTCVSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException STUDENTCVSERVICEWS_EXCEPTION;
    private final static QName STUDENTCVSERVICEWS_QNAME = new QName("http://serviceimpl.studentweb.sepro.org/", "StudentCVServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/StudentCVServicews/StudentCVServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTCVSERVICEWS_WSDL_LOCATION = url;
        STUDENTCVSERVICEWS_EXCEPTION = e;
    }

    public StudentCVServicews() {
        super(__getWsdlLocation(), STUDENTCVSERVICEWS_QNAME);
    }

    public StudentCVServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTCVSERVICEWS_QNAME, features);
    }

    public StudentCVServicews(URL wsdlLocation) {
        super(wsdlLocation, STUDENTCVSERVICEWS_QNAME);
    }

    public StudentCVServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTCVSERVICEWS_QNAME, features);
    }

    public StudentCVServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentCVServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentCVServicewsEndpoint
     */
    @WebEndpoint(name = "StudentCVServicewsImplPort")
    public StudentCVServicewsEndpoint getStudentCVServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "StudentCVServicewsImplPort"), StudentCVServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentCVServicewsEndpoint
     */
    @WebEndpoint(name = "StudentCVServicewsImplPort")
    public StudentCVServicewsEndpoint getStudentCVServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "StudentCVServicewsImplPort"), StudentCVServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTCVSERVICEWS_EXCEPTION!= null) {
            throw STUDENTCVSERVICEWS_EXCEPTION;
        }
        return STUDENTCVSERVICEWS_WSDL_LOCATION;
    }

}
