
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.studentweb.serviceapi.StudentPaymentDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentPaymentServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.studentweb.serviceapi.ObjectFactoryStudentPayment.class
})
public interface StudentPaymentServicewsEndpoint {


    /**
     * 
     * @param studentPaymentDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteStudentPaymentServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteStudentPaymentServicews")
    @ResponseWrapper(localName = "deleteStudentPaymentServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteStudentPaymentServicewsResponse")
    public void deleteStudentPaymentServicews(
        @WebParam(name = "studentPaymentDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentPaymentDto studentPaymentDto);

    /**
     * 
     * @param studentPaymentDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.StudentPaymentDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "createStudentPaymentServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateStudentPaymentServicews")
    @ResponseWrapper(localName = "createStudentPaymentServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateStudentPaymentServicewsResponse")
    public StudentPaymentDto createStudentPaymentServicews(
        @WebParam(name = "studentPaymentDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentPaymentDto studentPaymentDto);

    /**
     * 
     * @param studentPaymentDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.StudentPaymentDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "updateStudentPaymentServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateStudentPaymentServicews")
    @ResponseWrapper(localName = "updateStudentPaymentServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateStudentPaymentServicewsResponse")
    public StudentPaymentDto updateStudentPaymentServicews(
        @WebParam(name = "studentPaymentDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentPaymentDto studentPaymentDto);

    /**
     * 
     * @param studentPaymentDto
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.StudentPaymentDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "searchStudentPaymentServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentPaymentServicews")
    @ResponseWrapper(localName = "searchStudentPaymentServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentPaymentServicewsResponse")
    public List<StudentPaymentDto> searchStudentPaymentServicews(
        @WebParam(name = "studentPaymentDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentPaymentDto studentPaymentDto);

}
