
package org.sepro.studentweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentContactServicews", targetNamespace = "http://serviceimpl.studentweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/StudentContactServicews/StudentContactServicewsImpl?wsdl")
public class StudentContactServicews
    extends Service
{

    private final static URL STUDENTCONTACTSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException STUDENTCONTACTSERVICEWS_EXCEPTION;
    private final static QName STUDENTCONTACTSERVICEWS_QNAME = new QName("http://serviceimpl.studentweb.sepro.org/", "StudentContactServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/StudentContactServicews/StudentContactServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTCONTACTSERVICEWS_WSDL_LOCATION = url;
        STUDENTCONTACTSERVICEWS_EXCEPTION = e;
    }

    public StudentContactServicews() {
        super(__getWsdlLocation(), STUDENTCONTACTSERVICEWS_QNAME);
    }

    public StudentContactServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTCONTACTSERVICEWS_QNAME, features);
    }

    public StudentContactServicews(URL wsdlLocation) {
        super(wsdlLocation, STUDENTCONTACTSERVICEWS_QNAME);
    }

    public StudentContactServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTCONTACTSERVICEWS_QNAME, features);
    }

    public StudentContactServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentContactServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentContactServicewsEndpoint
     */
    @WebEndpoint(name = "StudentContactServicewsImplPort")
    public StudentContactServicewsEndpoint getStudentContactServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "StudentContactServicewsImplPort"), StudentContactServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentContactServicewsEndpoint
     */
    @WebEndpoint(name = "StudentContactServicewsImplPort")
    public StudentContactServicewsEndpoint getStudentContactServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "StudentContactServicewsImplPort"), StudentContactServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTCONTACTSERVICEWS_EXCEPTION!= null) {
            throw STUDENTCONTACTSERVICEWS_EXCEPTION;
        }
        return STUDENTCONTACTSERVICEWS_WSDL_LOCATION;
    }

}
