
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.studentweb.serviceapi.StudentContactDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentContactServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
   
    org.sepro.studentweb.serviceapi.ObjectFactoryStudentContact.class
})
public interface StudentContactServicewsEndpoint {


    /**
     * 
     * @param studentContactDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.StudentContactDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "createStudentContactServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateStudentContactServicews")
    @ResponseWrapper(localName = "createStudentContactServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateStudentContactServicewsResponse")
    public StudentContactDto createStudentContactServicews(
        @WebParam(name = "studentContactDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentContactDto studentContactDto);

    /**
     * 
     * @param studentContactDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.StudentContactDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "updateStudentContactServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateStudentContactServicews")
    @ResponseWrapper(localName = "updateStudentContactServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateStudentContactServicewsResponse")
    public StudentContactDto updateStudentContactServicews(
        @WebParam(name = "studentContactDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentContactDto studentContactDto);

    /**
     * 
     * @param studentContactDto
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.StudentContactDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "searchStudentContactServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentContactServicews")
    @ResponseWrapper(localName = "searchStudentContactServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentContactServicewsResponse")
    public List<StudentContactDto> searchStudentContactServicews(
        @WebParam(name = "studentContactDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentContactDto studentContactDto);

    /**
     * 
     * @param studentContactDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteStudentContactServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteStudentContactServicews")
    @ResponseWrapper(localName = "deleteStudentContactServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteStudentContactServicewsResponse")
    public void deleteStudentContactServicews(
        @WebParam(name = "studentContactDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentContactDto studentContactDto);

}
