
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.studentweb.serviceapi.StudentEventsDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentEventsServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.studentweb.serviceapi.ObjectFactoryStudentEvents.class
})
public interface StudentEventsServicewsEndpoint {


    /**
     * 
     * @param studentEventsDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.StudentEventsDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "createStudentEventsServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateStudentEventsServicews")
    @ResponseWrapper(localName = "createStudentEventsServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateStudentEventsServicewsResponse")
    public StudentEventsDto createStudentEventsServicews(
        @WebParam(name = "studentEventsDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentEventsDto studentEventsDto);

    /**
     * 
     * @param studentEventsDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteStudentEventsServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteStudentEventsServicews")
    @ResponseWrapper(localName = "deleteStudentEventsServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteStudentEventsServicewsResponse")
    public void deleteStudentEventsServicews(
        @WebParam(name = "studentEventsDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentEventsDto studentEventsDto);

    /**
     * 
     * @param studentEventsDto
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.StudentEventsDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "searchStudentEventsServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentEventsServicews")
    @ResponseWrapper(localName = "searchStudentEventsServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentEventsServicewsResponse")
    public List<StudentEventsDto> searchStudentEventsServicews(
        @WebParam(name = "studentEventsDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentEventsDto studentEventsDto);

    /**
     * 
     * @param studentEventsDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.StudentEventsDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "updateStudentEventsServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateStudentEventsServicews")
    @ResponseWrapper(localName = "updateStudentEventsServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateStudentEventsServicewsResponse")
    public StudentEventsDto updateStudentEventsServicews(
        @WebParam(name = "studentEventsDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentEventsDto studentEventsDto);

}
