
package org.sepro.studentweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentPaymentServicews", targetNamespace = "http://serviceimpl.studentweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/StudentPaymentServicews/StudentPaymentServicewsImpl?wsdl")
public class StudentPaymentServicews
    extends Service
{

    private final static URL STUDENTPAYMENTSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException STUDENTPAYMENTSERVICEWS_EXCEPTION;
    private final static QName STUDENTPAYMENTSERVICEWS_QNAME = new QName("http://serviceimpl.studentweb.sepro.org/", "StudentPaymentServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/StudentPaymentServicews/StudentPaymentServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTPAYMENTSERVICEWS_WSDL_LOCATION = url;
        STUDENTPAYMENTSERVICEWS_EXCEPTION = e;
    }

    public StudentPaymentServicews() {
        super(__getWsdlLocation(), STUDENTPAYMENTSERVICEWS_QNAME);
    }

    public StudentPaymentServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTPAYMENTSERVICEWS_QNAME, features);
    }

    public StudentPaymentServicews(URL wsdlLocation) {
        super(wsdlLocation, STUDENTPAYMENTSERVICEWS_QNAME);
    }

    public StudentPaymentServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTPAYMENTSERVICEWS_QNAME, features);
    }

    public StudentPaymentServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentPaymentServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentPaymentServicewsEndpoint
     */
    @WebEndpoint(name = "StudentPaymentServicewsImplPort")
    public StudentPaymentServicewsEndpoint getStudentPaymentServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "StudentPaymentServicewsImplPort"), StudentPaymentServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentPaymentServicewsEndpoint
     */
    @WebEndpoint(name = "StudentPaymentServicewsImplPort")
    public StudentPaymentServicewsEndpoint getStudentPaymentServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "StudentPaymentServicewsImplPort"), StudentPaymentServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTPAYMENTSERVICEWS_EXCEPTION!= null) {
            throw STUDENTPAYMENTSERVICEWS_EXCEPTION;
        }
        return STUDENTPAYMENTSERVICEWS_WSDL_LOCATION;
    }

}
