
package org.sepro.studentweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentExamServicews", targetNamespace = "http://serviceimpl.studentweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/StudentExamServicews/StudentExamServicewsImpl?wsdl")
public class StudentExamServicews
    extends Service
{

    private final static URL STUDENTEXAMSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException STUDENTEXAMSERVICEWS_EXCEPTION;
    private final static QName STUDENTEXAMSERVICEWS_QNAME = new QName("http://serviceimpl.studentweb.sepro.org/", "StudentExamServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/StudentExamServicews/StudentExamServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTEXAMSERVICEWS_WSDL_LOCATION = url;
        STUDENTEXAMSERVICEWS_EXCEPTION = e;
    }

    public StudentExamServicews() {
        super(__getWsdlLocation(), STUDENTEXAMSERVICEWS_QNAME);
    }

    public StudentExamServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTEXAMSERVICEWS_QNAME, features);
    }

    public StudentExamServicews(URL wsdlLocation) {
        super(wsdlLocation, STUDENTEXAMSERVICEWS_QNAME);
    }

    public StudentExamServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTEXAMSERVICEWS_QNAME, features);
    }

    public StudentExamServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentExamServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentExamServicewsEndpoint
     */
    @WebEndpoint(name = "StudentExamServicewsImplPort")
    public StudentExamServicewsEndpoint getStudentExamServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "StudentExamServicewsImplPort"), StudentExamServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentExamServicewsEndpoint
     */
    @WebEndpoint(name = "StudentExamServicewsImplPort")
    public StudentExamServicewsEndpoint getStudentExamServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "StudentExamServicewsImplPort"), StudentExamServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTEXAMSERVICEWS_EXCEPTION!= null) {
            throw STUDENTEXAMSERVICEWS_EXCEPTION;
        }
        return STUDENTEXAMSERVICEWS_WSDL_LOCATION;
    }

}
