
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.studentweb.serviceapi.StudentExamDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentExamServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.studentweb.serviceapi.ObjectFactoryStudentExam.class
})
public interface StudentExamServicewsEndpoint {


    /**
     * 
     * @param studentExamDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.StudentExamDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "updateStudentExamServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateStudentExamServicews")
    @ResponseWrapper(localName = "updateStudentExamServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateStudentExamServicewsResponse")
    public StudentExamDto updateStudentExamServicews(
        @WebParam(name = "studentExamDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentExamDto studentExamDto);

    /**
     * 
     * @param studentExamDto
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.StudentExamDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "searchStudentExamServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentExamServicews")
    @ResponseWrapper(localName = "searchStudentExamServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentExamServicewsResponse")
    public List<StudentExamDto> searchStudentExamServicews(
        @WebParam(name = "studentExamDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentExamDto studentExamDto);

    /**
     * 
     * @param studentExamDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.StudentExamDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "createStudentExamServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateStudentExamServicews")
    @ResponseWrapper(localName = "createStudentExamServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateStudentExamServicewsResponse")
    public StudentExamDto createStudentExamServicews(
        @WebParam(name = "studentExamDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentExamDto studentExamDto);

    /**
     * 
     * @param studentExamDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteStudentExamServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteStudentExamServicews")
    @ResponseWrapper(localName = "deleteStudentExamServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteStudentExamServicewsResponse")
    public void deleteStudentExamServicews(
        @WebParam(name = "studentExamDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentExamDto studentExamDto);

}
