
package org.sepro.studentweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentServicews", targetNamespace = "http://serviceimpl.studentweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/StudentServicews/StudentServicewsImpl?wsdl")
public class StudentServicews
    extends Service
{

    private final static URL STUDENTSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException STUDENTSERVICEWS_EXCEPTION;
    private final static QName STUDENTSERVICEWS_QNAME = new QName("http://serviceimpl.studentweb.sepro.org/", "StudentServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/StudentServicews/StudentServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTSERVICEWS_WSDL_LOCATION = url;
        STUDENTSERVICEWS_EXCEPTION = e;
    }

    public StudentServicews() {
        super(__getWsdlLocation(), STUDENTSERVICEWS_QNAME);
    }

    public StudentServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTSERVICEWS_QNAME, features);
    }

    public StudentServicews(URL wsdlLocation) {
        super(wsdlLocation, STUDENTSERVICEWS_QNAME);
    }

    public StudentServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTSERVICEWS_QNAME, features);
    }

    public StudentServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentServicewsEndpoint
     */
    @WebEndpoint(name = "StudentServicewsImplPort")
    public StudentServicewsEndpoint getStudentServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "StudentServicewsImplPort"), StudentServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentServicewsEndpoint
     */
    @WebEndpoint(name = "StudentServicewsImplPort")
    public StudentServicewsEndpoint getStudentServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "StudentServicewsImplPort"), StudentServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTSERVICEWS_EXCEPTION!= null) {
            throw STUDENTSERVICEWS_EXCEPTION;
        }
        return STUDENTSERVICEWS_WSDL_LOCATION;
    }

}
