
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.studentweb.serviceapi.StudentProgramDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentProgramServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.studentweb.serviceapi.ObjectFactoryStudentProgram.class
})
public interface StudentProgramServicewsEndpoint {


    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.StudentProgramDto>
     */
    @WebMethod(operationName = "SearchStudentProgramDtoServicews")
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "SearchStudentProgramDtoServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentProgramDtoServicews")
    @ResponseWrapper(localName = "SearchStudentProgramDtoServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentProgramDtoServicewsResponse")
    public List<StudentProgramDto> searchStudentProgramDtoServicews();

}
