
package org.sepro.studentweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.studentweb.serviceapi.StudentExamGroupDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentExamGroupServicewsEndpoint", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.studentweb.serviceapi.ObjectFactoryStudentExamGroup.class
})
public interface StudentExamGroupServicewsEndpoint {


    /**
     * 
     * @param studentExamGroupDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.StudentExamGroupDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "updateStudentExamGroupServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateStudentExamGroupServicews")
    @ResponseWrapper(localName = "updateStudentExamGroupServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.UpdateStudentExamGroupServicewsResponse")
    public StudentExamGroupDto updateStudentExamGroupServicews(
        @WebParam(name = "studentExamGroupDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentExamGroupDto studentExamGroupDto);

    /**
     * 
     * @param studentExamGroupDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteStudentExamGroupServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteStudentExamGroupServicews")
    @ResponseWrapper(localName = "deleteStudentExamGroupServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.DeleteStudentExamGroupServicewsResponse")
    public void deleteStudentExamGroupServicews(
        @WebParam(name = "studentExamGroupDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentExamGroupDto studentExamGroupDto);

    /**
     * 
     * @param studentExamGroupDto
     * @return
     *     returns java.util.List<org.sepro.studentweb.serviceapi.StudentExamGroupDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "searchStudentExamGroupServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentExamGroupServicews")
    @ResponseWrapper(localName = "searchStudentExamGroupServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.SearchStudentExamGroupServicewsResponse")
    public List<StudentExamGroupDto> searchStudentExamGroupServicews(
        @WebParam(name = "studentExamGroupDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentExamGroupDto studentExamGroupDto);

    /**
     * 
     * @param studentExamGroupDto
     * @return
     *     returns org.sepro.studentweb.serviceapi.StudentExamGroupDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.studentweb.sepro.org/")
    @RequestWrapper(localName = "createStudentExamGroupServicews", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateStudentExamGroupServicews")
    @ResponseWrapper(localName = "createStudentExamGroupServicewsResponse", targetNamespace = "http://serviceapi.studentweb.sepro.org/", className = "org.sepro.studentweb.serviceapi.CreateStudentExamGroupServicewsResponse")
    public StudentExamGroupDto createStudentExamGroupServicews(
        @WebParam(name = "studentExamGroupDto", targetNamespace = "http://serviceapi.studentweb.sepro.org/")
        StudentExamGroupDto studentExamGroupDto);

}
