
package org.sepro.studentweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TeacherPresenceServicews", targetNamespace = "http://serviceimpl.studentweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/TeacherPresenceServicews/TeacherPresenceServicewsImpl?wsdl")
public class TeacherPresenceServicews
    extends Service
{

    private final static URL TEACHERPRESENCESERVICEWS_WSDL_LOCATION;
    private final static WebServiceException TEACHERPRESENCESERVICEWS_EXCEPTION;
    private final static QName TEACHERPRESENCESERVICEWS_QNAME = new QName("http://serviceimpl.studentweb.sepro.org/", "TeacherPresenceServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/TeacherPresenceServicews/TeacherPresenceServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TEACHERPRESENCESERVICEWS_WSDL_LOCATION = url;
        TEACHERPRESENCESERVICEWS_EXCEPTION = e;
    }

    public TeacherPresenceServicews() {
        super(__getWsdlLocation(), TEACHERPRESENCESERVICEWS_QNAME);
    }

    public TeacherPresenceServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEACHERPRESENCESERVICEWS_QNAME, features);
    }

    public TeacherPresenceServicews(URL wsdlLocation) {
        super(wsdlLocation, TEACHERPRESENCESERVICEWS_QNAME);
    }

    public TeacherPresenceServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEACHERPRESENCESERVICEWS_QNAME, features);
    }

    public TeacherPresenceServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TeacherPresenceServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TeacherPresenceServicewsEndpoint
     */
    @WebEndpoint(name = "TeacherPresenceServicewsImplPort")
    public TeacherPresenceServicewsEndpoint getTeacherPresenceServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "TeacherPresenceServicewsImplPort"), TeacherPresenceServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TeacherPresenceServicewsEndpoint
     */
    @WebEndpoint(name = "TeacherPresenceServicewsImplPort")
    public TeacherPresenceServicewsEndpoint getTeacherPresenceServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.studentweb.sepro.org/", "TeacherPresenceServicewsImplPort"), TeacherPresenceServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEACHERPRESENCESERVICEWS_EXCEPTION!= null) {
            throw TEACHERPRESENCESERVICEWS_EXCEPTION;
        }
        return TEACHERPRESENCESERVICEWS_WSDL_LOCATION;
    }

}
