
package org.sepro.parameterweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.parameterweb.serviceapi.AcademicModuleDto;
import org.sepro.parameterweb.serviceapi.ObjectFactoryAcademic;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AcademicModuleDtoServicewsEndpoint", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactoryAcademic.class
})
public interface AcademicModuleDtoServicewsEndpoint {


    /**
     * 
     * @param academicModuleDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAcademicModuleServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteAcademicModuleServicews")
    @ResponseWrapper(localName = "deleteAcademicModuleServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteAcademicModuleServicewsResponse")
    public void deleteAcademicModuleServicews(
        @WebParam(name = "academicModuleDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        AcademicModuleDto academicModuleDto);

    /**
     * 
     * @param academicModuleDto
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.AcademicModuleDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchAcademicModuleServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchAcademicModuleServicews")
    @ResponseWrapper(localName = "searchAcademicModuleServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchAcademicModuleServicewsResponse")
    public List<AcademicModuleDto> searchAcademicModuleServicews(
        @WebParam(name = "academicModuleDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        AcademicModuleDto academicModuleDto);

    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.AcademicModuleDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getAllAcademicModuleServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllAcademicModuleServicews")
    @ResponseWrapper(localName = "getAllAcademicModuleServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllAcademicModuleServicewsResponse")
    public List<AcademicModuleDto> getAllAcademicModuleServicews();

    /**
     * 
     * @param academicModuleDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.AcademicModuleDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "createAcademicModuleServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateAcademicModuleServicews")
    @ResponseWrapper(localName = "createAcademicModuleServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateAcademicModuleServicewsResponse")
    public AcademicModuleDto createAcademicModuleServicews(
        @WebParam(name = "academicModuleDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        AcademicModuleDto academicModuleDto);

    /**
     * 
     * @param academicModuleDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.AcademicModuleDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "updateAcademicModuleServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateAcademicModuleServicews")
    @ResponseWrapper(localName = "updateAcademicModuleServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateAcademicModuleServicewsResponse")
    public AcademicModuleDto updateAcademicModuleServicews(
        @WebParam(name = "academicModuleDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        AcademicModuleDto academicModuleDto);

}
