
package org.sepro.parameterweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.parameterweb.serviceapi.BuildingDto;
import org.sepro.parameterweb.serviceapi.ObjectFactoryBuilding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BuildingServicewsEndpoint", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactoryBuilding.class
})
public interface BuildingServicewsEndpoint {


    /**
     * 
     * @param buildingDto
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.BuildingDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchBuildingServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchBuildingServicews")
    @ResponseWrapper(localName = "searchBuildingServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchBuildingServicewsResponse")
    public List<BuildingDto> searchBuildingServicews(
        @WebParam(name = "buildingDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        BuildingDto buildingDto);

    /**
     * 
     * @param buildingDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.BuildingDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "createBuildingServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateBuildingServicews")
    @ResponseWrapper(localName = "createBuildingServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateBuildingServicewsResponse")
    public BuildingDto createBuildingServicews(
        @WebParam(name = "buildingDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        BuildingDto buildingDto);

    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.BuildingDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getAllBuildingServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllBuildingServicews")
    @ResponseWrapper(localName = "getAllBuildingServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllBuildingServicewsResponse")
    public List<BuildingDto> getAllBuildingServicews();

    /**
     * 
     * @param buildingDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.BuildingDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "updateBuildingServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateBuildingServicews")
    @ResponseWrapper(localName = "updateBuildingServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateBuildingServicewsResponse")
    public BuildingDto updateBuildingServicews(
        @WebParam(name = "buildingDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        BuildingDto buildingDto);

    /**
     * 
     * @param buildingDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteBuildingServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteBuildingServicews")
    @ResponseWrapper(localName = "deleteBuildingServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteBuildingServicewsResponse")
    public void deleteBuildingServicews(
        @WebParam(name = "buildingDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        BuildingDto buildingDto);

    /**
     * 
     * @param pageSize
     * @param page
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.BuildingDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getPageAllBuildingServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetPageAllBuildingServicews")
    @ResponseWrapper(localName = "getPageAllBuildingServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetPageAllBuildingServicewsResponse")
    public List<BuildingDto> getPageAllBuildingServicews(
        @WebParam(name = "page", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int pageSize);

    /**
     * 
     * @param pageSize
     * @param page
     * @param buildingDto
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.BuildingDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchPageBuildingServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchPageBuildingServicews")
    @ResponseWrapper(localName = "searchPageBuildingServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchPageBuildingServicewsResponse")
    public List<BuildingDto> searchPageBuildingServicews(
        @WebParam(name = "buildingDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        BuildingDto buildingDto,
        @WebParam(name = "page", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int pageSize);

}
