
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BuildingServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/BuildingServicews/BuildingServicewsImpl?wsdl")
public class BuildingServicews
    extends Service
{

    private final static URL BUILDINGSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException BUILDINGSERVICEWS_EXCEPTION;
    private final static QName BUILDINGSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "BuildingServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/BuildingServicews/BuildingServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BUILDINGSERVICEWS_WSDL_LOCATION = url;
        BUILDINGSERVICEWS_EXCEPTION = e;
    }

    public BuildingServicews() {
        super(__getWsdlLocation(), BUILDINGSERVICEWS_QNAME);
    }

    public BuildingServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), BUILDINGSERVICEWS_QNAME, features);
    }

    public BuildingServicews(URL wsdlLocation) {
        super(wsdlLocation, BUILDINGSERVICEWS_QNAME);
    }

    public BuildingServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BUILDINGSERVICEWS_QNAME, features);
    }

    public BuildingServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BuildingServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BuildingServicewsEndpoint
     */
    @WebEndpoint(name = "BuildingServicewsImplPort")
    public BuildingServicewsEndpoint getBuildingServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "BuildingServicewsImplPort"), BuildingServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BuildingServicewsEndpoint
     */
    @WebEndpoint(name = "BuildingServicewsImplPort")
    public BuildingServicewsEndpoint getBuildingServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "BuildingServicewsImplPort"), BuildingServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BUILDINGSERVICEWS_EXCEPTION!= null) {
            throw BUILDINGSERVICEWS_EXCEPTION;
        }
        return BUILDINGSERVICEWS_WSDL_LOCATION;
    }

}
