
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CityServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/CityServicews/CityServicewsImpl?wsdl")
public class CityServicews
    extends Service
{

    private final static URL CITYSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException CITYSERVICEWS_EXCEPTION;
    private final static QName CITYSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "CityServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/CityServicews/CityServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CITYSERVICEWS_WSDL_LOCATION = url;
        CITYSERVICEWS_EXCEPTION = e;
    }

    public CityServicews() {
        super(__getWsdlLocation(), CITYSERVICEWS_QNAME);
    }

    public CityServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), CITYSERVICEWS_QNAME, features);
    }

    public CityServicews(URL wsdlLocation) {
        super(wsdlLocation, CITYSERVICEWS_QNAME);
    }

    public CityServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CITYSERVICEWS_QNAME, features);
    }

    public CityServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CityServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CityServicewsEndpoint
     */
    @WebEndpoint(name = "CityServicewsImplPort")
    public CityServicewsEndpoint getCityServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "CityServicewsImplPort"), CityServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CityServicewsEndpoint
     */
    @WebEndpoint(name = "CityServicewsImplPort")
    public CityServicewsEndpoint getCityServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "CityServicewsImplPort"), CityServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CITYSERVICEWS_EXCEPTION!= null) {
            throw CITYSERVICEWS_EXCEPTION;
        }
        return CITYSERVICEWS_WSDL_LOCATION;
    }

}
