
package org.sepro.parameterweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.parameterweb.serviceapi.ClasseDto;
import org.sepro.parameterweb.serviceapi.ObjectFactoryClasse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClasseServicewsEndpoint", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactoryClasse.class
})
public interface ClasseServicewsEndpoint {


    /**
     * 
     * @param classeDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.ClasseDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "updateClasseServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateClasseServicews")
    @ResponseWrapper(localName = "updateClasseServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateClasseServicewsResponse")
    public ClasseDto updateClasseServicews(
        @WebParam(name = "classeDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ClasseDto classeDto);

    /**
     * 
     * @param classeDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.ClasseDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "createClasseServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateClasseServicews")
    @ResponseWrapper(localName = "createClasseServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateClasseServicewsResponse")
    public ClasseDto createClasseServicews(
        @WebParam(name = "classeDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ClasseDto classeDto);

    /**
     * 
     * @param classeDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteClasseServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteClasseServicews")
    @ResponseWrapper(localName = "deleteClasseServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteClasseServicewsResponse")
    public void deleteClasseServicews(
        @WebParam(name = "classeDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ClasseDto classeDto);

    /**
     * 
     * @param pageSize
     * @param page
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.ClasseDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getPageAllClasseServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetPageAllClasseServicews")
    @ResponseWrapper(localName = "getPageAllClasseServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetPageAllClasseServicewsResponse")
    public List<ClasseDto> getPageAllClasseServicews(
        @WebParam(name = "page", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int pageSize);

    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.ClasseDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getAllClasseServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllClasseServicews")
    @ResponseWrapper(localName = "getAllClasseServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllClasseServicewsResponse")
    public List<ClasseDto> getAllClasseServicews();

    /**
     * 
     * @param classeDto
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.ClasseDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchClasseServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchClasseServicews")
    @ResponseWrapper(localName = "searchClasseServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchClasseServicewsResponse")
    public List<ClasseDto> searchClasseServicews(
        @WebParam(name = "classeDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ClasseDto classeDto);

    /**
     * 
     * @param classeDto
     * @param pageSize
     * @param page
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.ClasseDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchPageClasseServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchPageClasseServicews")
    @ResponseWrapper(localName = "searchPageClasseServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchPageClasseServicewsResponse")
    public List<ClasseDto> searchPageClasseServicews(
        @WebParam(name = "classeDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ClasseDto classeDto,
        @WebParam(name = "page", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int pageSize);

}
