
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClasseServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ClasseServicews/ClasseServicewsImpl?wsdl")
public class ClasseServicews
    extends Service
{

    private final static URL CLASSESERVICEWS_WSDL_LOCATION;
    private final static WebServiceException CLASSESERVICEWS_EXCEPTION;
    private final static QName CLASSESERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "ClasseServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ClasseServicews/ClasseServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLASSESERVICEWS_WSDL_LOCATION = url;
        CLASSESERVICEWS_EXCEPTION = e;
    }

    public ClasseServicews() {
        super(__getWsdlLocation(), CLASSESERVICEWS_QNAME);
    }

    public ClasseServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLASSESERVICEWS_QNAME, features);
    }

    public ClasseServicews(URL wsdlLocation) {
        super(wsdlLocation, CLASSESERVICEWS_QNAME);
    }

    public ClasseServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLASSESERVICEWS_QNAME, features);
    }

    public ClasseServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClasseServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClasseServicewsEndpoint
     */
    @WebEndpoint(name = "ClasseServicewsImplPort")
    public ClasseServicewsEndpoint getClasseServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "ClasseServicewsImplPort"), ClasseServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClasseServicewsEndpoint
     */
    @WebEndpoint(name = "ClasseServicewsImplPort")
    public ClasseServicewsEndpoint getClasseServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "ClasseServicewsImplPort"), ClasseServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLASSESERVICEWS_EXCEPTION!= null) {
            throw CLASSESERVICEWS_EXCEPTION;
        }
        return CLASSESERVICEWS_WSDL_LOCATION;
    }

}
