
package org.sepro.parameterweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.parameterweb.serviceapi.CleanHoursDto;
import org.sepro.parameterweb.serviceapi.ObjectFactoryCleanHours;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CleanHoursServicewsEndpoint", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactoryCleanHours.class
})
public interface CleanHoursServicewsEndpoint {


    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.CleanHoursDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getAllCleanHoursServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllCleanHoursServicews")
    @ResponseWrapper(localName = "getAllCleanHoursServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllCleanHoursServicewsResponse")
    public List<CleanHoursDto> getAllCleanHoursServicews();

}
