
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CleanHoursServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/CleanHoursServicews/CleanHoursServicewsImpl?wsdl")
public class CleanHoursServicews
    extends Service
{

    private final static URL CLEANHOURSSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException CLEANHOURSSERVICEWS_EXCEPTION;
    private final static QName CLEANHOURSSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "CleanHoursServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/CleanHoursServicews/CleanHoursServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLEANHOURSSERVICEWS_WSDL_LOCATION = url;
        CLEANHOURSSERVICEWS_EXCEPTION = e;
    }

    public CleanHoursServicews() {
        super(__getWsdlLocation(), CLEANHOURSSERVICEWS_QNAME);
    }

    public CleanHoursServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLEANHOURSSERVICEWS_QNAME, features);
    }

    public CleanHoursServicews(URL wsdlLocation) {
        super(wsdlLocation, CLEANHOURSSERVICEWS_QNAME);
    }

    public CleanHoursServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLEANHOURSSERVICEWS_QNAME, features);
    }

    public CleanHoursServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CleanHoursServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CleanHoursServicewsEndpoint
     */
    @WebEndpoint(name = "CleanHoursServicewsImplPort")
    public CleanHoursServicewsEndpoint getCleanHoursServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "CleanHoursServicewsImplPort"), CleanHoursServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CleanHoursServicewsEndpoint
     */
    @WebEndpoint(name = "CleanHoursServicewsImplPort")
    public CleanHoursServicewsEndpoint getCleanHoursServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "CleanHoursServicewsImplPort"), CleanHoursServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLEANHOURSSERVICEWS_EXCEPTION!= null) {
            throw CLEANHOURSSERVICEWS_EXCEPTION;
        }
        return CLEANHOURSSERVICEWS_WSDL_LOCATION;
    }

}
