
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CountryServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/CountryServicews/CountryServicewsImpl?wsdl")
public class CountryServicews
    extends Service
{

    private final static URL COUNTRYSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException COUNTRYSERVICEWS_EXCEPTION;
    private final static QName COUNTRYSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "CountryServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/CountryServicews/CountryServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COUNTRYSERVICEWS_WSDL_LOCATION = url;
        COUNTRYSERVICEWS_EXCEPTION = e;
    }

    public CountryServicews() {
        super(__getWsdlLocation(), COUNTRYSERVICEWS_QNAME);
    }

    public CountryServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTRYSERVICEWS_QNAME, features);
    }

    public CountryServicews(URL wsdlLocation) {
        super(wsdlLocation, COUNTRYSERVICEWS_QNAME);
    }

    public CountryServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTRYSERVICEWS_QNAME, features);
    }

    public CountryServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountryServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CountryServicewsEndpoint
     */
    @WebEndpoint(name = "CountryServicewsImplPort")
    public CountryServicewsEndpoint getCountryServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "CountryServicewsImplPort"), CountryServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountryServicewsEndpoint
     */
    @WebEndpoint(name = "CountryServicewsImplPort")
    public CountryServicewsEndpoint getCountryServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "CountryServicewsImplPort"), CountryServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTRYSERVICEWS_EXCEPTION!= null) {
            throw COUNTRYSERVICEWS_EXCEPTION;
        }
        return COUNTRYSERVICEWS_WSDL_LOCATION;
    }

}
