
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CourseSubjectDtoServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/CourseSubjectDtoServicews/CourseSubjectDtoServicewsImpl?wsdl")
public class CourseSubjectDtoServicews
    extends Service
{

    private final static URL COURSESUBJECTDTOSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException COURSESUBJECTDTOSERVICEWS_EXCEPTION;
    private final static QName COURSESUBJECTDTOSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "CourseSubjectDtoServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/CourseSubjectDtoServicews/CourseSubjectDtoServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COURSESUBJECTDTOSERVICEWS_WSDL_LOCATION = url;
        COURSESUBJECTDTOSERVICEWS_EXCEPTION = e;
    }

    public CourseSubjectDtoServicews() {
        super(__getWsdlLocation(), COURSESUBJECTDTOSERVICEWS_QNAME);
    }

    public CourseSubjectDtoServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), COURSESUBJECTDTOSERVICEWS_QNAME, features);
    }

    public CourseSubjectDtoServicews(URL wsdlLocation) {
        super(wsdlLocation, COURSESUBJECTDTOSERVICEWS_QNAME);
    }

    public CourseSubjectDtoServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COURSESUBJECTDTOSERVICEWS_QNAME, features);
    }

    public CourseSubjectDtoServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourseSubjectDtoServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CourseSubjectDtoServicewsEndpoint
     */
    @WebEndpoint(name = "CourseSubjectDtoServicewsImplPort")
    public CourseSubjectDtoServicewsEndpoint getCourseSubjectDtoServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "CourseSubjectDtoServicewsImplPort"), CourseSubjectDtoServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CourseSubjectDtoServicewsEndpoint
     */
    @WebEndpoint(name = "CourseSubjectDtoServicewsImplPort")
    public CourseSubjectDtoServicewsEndpoint getCourseSubjectDtoServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "CourseSubjectDtoServicewsImplPort"), CourseSubjectDtoServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COURSESUBJECTDTOSERVICEWS_EXCEPTION!= null) {
            throw COURSESUBJECTDTOSERVICEWS_EXCEPTION;
        }
        return COURSESUBJECTDTOSERVICEWS_WSDL_LOCATION;
    }

}
