
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CurriculumDtoServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/CurriculumDtoServicews/CurriculumDtoServicewsImpl?wsdl")
public class CurriculumDtoServicews
    extends Service
{

    private final static URL CURRICULUMDTOSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException CURRICULUMDTOSERVICEWS_EXCEPTION;
    private final static QName CURRICULUMDTOSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "CurriculumDtoServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/CurriculumDtoServicews/CurriculumDtoServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CURRICULUMDTOSERVICEWS_WSDL_LOCATION = url;
        CURRICULUMDTOSERVICEWS_EXCEPTION = e;
    }

    public CurriculumDtoServicews() {
        super(__getWsdlLocation(), CURRICULUMDTOSERVICEWS_QNAME);
    }

    public CurriculumDtoServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), CURRICULUMDTOSERVICEWS_QNAME, features);
    }

    public CurriculumDtoServicews(URL wsdlLocation) {
        super(wsdlLocation, CURRICULUMDTOSERVICEWS_QNAME);
    }

    public CurriculumDtoServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CURRICULUMDTOSERVICEWS_QNAME, features);
    }

    public CurriculumDtoServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CurriculumDtoServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CurriculumDtoServicewsEndpoint
     */
    @WebEndpoint(name = "CurriculumDtoServicewsImplPort")
    public CurriculumDtoServicewsEndpoint getCurriculumDtoServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "CurriculumDtoServicewsImplPort"), CurriculumDtoServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CurriculumDtoServicewsEndpoint
     */
    @WebEndpoint(name = "CurriculumDtoServicewsImplPort")
    public CurriculumDtoServicewsEndpoint getCurriculumDtoServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "CurriculumDtoServicewsImplPort"), CurriculumDtoServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CURRICULUMDTOSERVICEWS_EXCEPTION!= null) {
            throw CURRICULUMDTOSERVICEWS_EXCEPTION;
        }
        return CURRICULUMDTOSERVICEWS_WSDL_LOCATION;
    }

}
