
package org.sepro.parameterweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.parameterweb.serviceapi.CurriculumDto;
import org.sepro.parameterweb.serviceapi.ObjectFactoryCurriculum;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CurriculumDtoServicewsEndpoint", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactoryCurriculum.class
})
public interface CurriculumDtoServicewsEndpoint {


    /**
     * 
     * @param curriculumDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.CurriculumDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "updateCurriculumDServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateCurriculumDServicews")
    @ResponseWrapper(localName = "updateCurriculumDServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateCurriculumDServicewsResponse")
    public CurriculumDto updateCurriculumDServicews(
        @WebParam(name = "curriculumDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        CurriculumDto curriculumDto);

    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.CurriculumDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getAllCurriculumDServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllCurriculumDServicews")
    @ResponseWrapper(localName = "getAllCurriculumDServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllCurriculumDServicewsResponse")
    public List<CurriculumDto> getAllCurriculumDServicews();

    /**
     * 
     * @param curriculumDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.CurriculumDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "createCurriculumDServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateCurriculumDServicews")
    @ResponseWrapper(localName = "createCurriculumDServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateCurriculumDServicewsResponse")
    public CurriculumDto createCurriculumDServicews(
        @WebParam(name = "curriculumDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        CurriculumDto curriculumDto);

    /**
     * 
     * @param curriculumDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteCurriculumDServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteCurriculumDServicews")
    @ResponseWrapper(localName = "deleteCurriculumDServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteCurriculumDServicewsResponse")
    public void deleteCurriculumDServicews(
        @WebParam(name = "curriculumDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        CurriculumDto curriculumDto);

    /**
     * 
     * @param curriculumDto
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.CurriculumDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchCurriculumDServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchCurriculumDServicews")
    @ResponseWrapper(localName = "searchCurriculumDServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchCurriculumDServicewsResponse")
    public List<CurriculumDto> searchCurriculumDServicews(
        @WebParam(name = "curriculumDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        CurriculumDto curriculumDto);

}
