
package org.sepro.parameterweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.parameterweb.serviceapi.DaysofWeekDto;
import org.sepro.parameterweb.serviceapi.ObjectFactoryDaysofWeek;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DaysofWeekServicewsEndpoint", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactoryDaysofWeek.class
})
public interface DaysofWeekServicewsEndpoint {


    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.DaysofWeekDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getAllDaysofWeekServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllDaysofWeekServicews")
    @ResponseWrapper(localName = "getAllDaysofWeekServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllDaysofWeekServicewsResponse")
    public List<DaysofWeekDto> getAllDaysofWeekServicews();

}
