
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DaysofWeekServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/DaysofWeekServicews/DaysofWeekServicewsImpl?wsdl")
public class DaysofWeekServicews
    extends Service
{

    private final static URL DAYSOFWEEKSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException DAYSOFWEEKSERVICEWS_EXCEPTION;
    private final static QName DAYSOFWEEKSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "DaysofWeekServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/DaysofWeekServicews/DaysofWeekServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DAYSOFWEEKSERVICEWS_WSDL_LOCATION = url;
        DAYSOFWEEKSERVICEWS_EXCEPTION = e;
    }

    public DaysofWeekServicews() {
        super(__getWsdlLocation(), DAYSOFWEEKSERVICEWS_QNAME);
    }

    public DaysofWeekServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), DAYSOFWEEKSERVICEWS_QNAME, features);
    }

    public DaysofWeekServicews(URL wsdlLocation) {
        super(wsdlLocation, DAYSOFWEEKSERVICEWS_QNAME);
    }

    public DaysofWeekServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DAYSOFWEEKSERVICEWS_QNAME, features);
    }

    public DaysofWeekServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DaysofWeekServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DaysofWeekServicewsEndpoint
     */
    @WebEndpoint(name = "DaysofWeekServicewsImplPort")
    public DaysofWeekServicewsEndpoint getDaysofWeekServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "DaysofWeekServicewsImplPort"), DaysofWeekServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DaysofWeekServicewsEndpoint
     */
    @WebEndpoint(name = "DaysofWeekServicewsImplPort")
    public DaysofWeekServicewsEndpoint getDaysofWeekServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "DaysofWeekServicewsImplPort"), DaysofWeekServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DAYSOFWEEKSERVICEWS_EXCEPTION!= null) {
            throw DAYSOFWEEKSERVICEWS_EXCEPTION;
        }
        return DAYSOFWEEKSERVICEWS_WSDL_LOCATION;
    }

}
