
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EstablishmentServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/EstablishmentServicews/EstablishmentServicewsImpl?wsdl")
public class EstablishmentServicews
    extends Service
{

    private final static URL ESTABLISHMENTSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException ESTABLISHMENTSERVICEWS_EXCEPTION;
    private final static QName ESTABLISHMENTSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "EstablishmentServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/EstablishmentServicews/EstablishmentServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESTABLISHMENTSERVICEWS_WSDL_LOCATION = url;
        ESTABLISHMENTSERVICEWS_EXCEPTION = e;
    }

    public EstablishmentServicews() {
        super(__getWsdlLocation(), ESTABLISHMENTSERVICEWS_QNAME);
    }

    public EstablishmentServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESTABLISHMENTSERVICEWS_QNAME, features);
    }

    public EstablishmentServicews(URL wsdlLocation) {
        super(wsdlLocation, ESTABLISHMENTSERVICEWS_QNAME);
    }

    public EstablishmentServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESTABLISHMENTSERVICEWS_QNAME, features);
    }

    public EstablishmentServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstablishmentServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EstablishmentServicewsEndpoint
     */
    @WebEndpoint(name = "EstablishmentServicewsImplPort")
    public EstablishmentServicewsEndpoint getEstablishmentServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "EstablishmentServicewsImplPort"), EstablishmentServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstablishmentServicewsEndpoint
     */
    @WebEndpoint(name = "EstablishmentServicewsImplPort")
    public EstablishmentServicewsEndpoint getEstablishmentServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "EstablishmentServicewsImplPort"), EstablishmentServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESTABLISHMENTSERVICEWS_EXCEPTION!= null) {
            throw ESTABLISHMENTSERVICEWS_EXCEPTION;
        }
        return ESTABLISHMENTSERVICEWS_WSDL_LOCATION;
    }

}
