
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LanguageServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/LanguageServicews/LanguageServicewsImpl?wsdl")
public class LanguageServicews
    extends Service
{

    private final static URL LANGUAGESERVICEWS_WSDL_LOCATION;
    private final static WebServiceException LANGUAGESERVICEWS_EXCEPTION;
    private final static QName LANGUAGESERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "LanguageServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/LanguageServicews/LanguageServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LANGUAGESERVICEWS_WSDL_LOCATION = url;
        LANGUAGESERVICEWS_EXCEPTION = e;
    }

    public LanguageServicews() {
        super(__getWsdlLocation(), LANGUAGESERVICEWS_QNAME);
    }

    public LanguageServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), LANGUAGESERVICEWS_QNAME, features);
    }

    public LanguageServicews(URL wsdlLocation) {
        super(wsdlLocation, LANGUAGESERVICEWS_QNAME);
    }

    public LanguageServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LANGUAGESERVICEWS_QNAME, features);
    }

    public LanguageServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LanguageServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LanguageServicewsEndpoint
     */
    @WebEndpoint(name = "LanguageServicewsImplPort")
    public LanguageServicewsEndpoint getLanguageServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "LanguageServicewsImplPort"), LanguageServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LanguageServicewsEndpoint
     */
    @WebEndpoint(name = "LanguageServicewsImplPort")
    public LanguageServicewsEndpoint getLanguageServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "LanguageServicewsImplPort"), LanguageServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LANGUAGESERVICEWS_EXCEPTION!= null) {
            throw LANGUAGESERVICEWS_EXCEPTION;
        }
        return LANGUAGESERVICEWS_WSDL_LOCATION;
    }

}
