
package org.sepro.parameterweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.parameterweb.serviceapi.ModuleCalendarDto;
import org.sepro.parameterweb.serviceapi.ObjectFactoryModuleCalendar;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ModuleCalendarDtoServicewsEndpoint", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactoryModuleCalendar.class
})
public interface ModuleCalendarDtoServicewsEndpoint {


    /**
     * 
     * @param moduleCalendarDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.ModuleCalendarDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "createModuleCalendarServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateModuleCalendarServicews")
    @ResponseWrapper(localName = "createModuleCalendarServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateModuleCalendarServicewsResponse")
    public ModuleCalendarDto createModuleCalendarServicews(
        @WebParam(name = "moduleCalendarDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ModuleCalendarDto moduleCalendarDto);

    /**
     * 
     * @param moduleCalendarDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteModuleCalendarServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteModuleCalendarServicews")
    @ResponseWrapper(localName = "deleteModuleCalendarServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteModuleCalendarServicewsResponse")
    public void deleteModuleCalendarServicews(
        @WebParam(name = "moduleCalendarDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ModuleCalendarDto moduleCalendarDto);

    /**
     * 
     * @param moduleCalendarDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.ModuleCalendarDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "updateModuleCalendarServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateModuleCalendarServicews")
    @ResponseWrapper(localName = "updateModuleCalendarServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateModuleCalendarServicewsResponse")
    public ModuleCalendarDto updateModuleCalendarServicews(
        @WebParam(name = "moduleCalendarDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ModuleCalendarDto moduleCalendarDto);

    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.ModuleCalendarDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getAllModuleCalendarServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllModuleCalendarServicews")
    @ResponseWrapper(localName = "getAllModuleCalendarServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllModuleCalendarServicewsResponse")
    public List<ModuleCalendarDto> getAllModuleCalendarServicews();

    /**
     * 
     * @param moduleCalendarDto
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.ModuleCalendarDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchModuleCalendarServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchModuleCalendarServicews")
    @ResponseWrapper(localName = "searchModuleCalendarServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchModuleCalendarServicewsResponse")
    public List<ModuleCalendarDto> searchModuleCalendarServicews(
        @WebParam(name = "moduleCalendarDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ModuleCalendarDto moduleCalendarDto);

}
