
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ModuleCalendarDtoServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ModuleCalendarDtoServicews/ModuleCalendarDtoServicewsImpl?wsdl")
public class ModuleCalendarDtoServicews
    extends Service
{

    private final static URL MODULECALENDARDTOSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException MODULECALENDARDTOSERVICEWS_EXCEPTION;
    private final static QName MODULECALENDARDTOSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "ModuleCalendarDtoServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ModuleCalendarDtoServicews/ModuleCalendarDtoServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODULECALENDARDTOSERVICEWS_WSDL_LOCATION = url;
        MODULECALENDARDTOSERVICEWS_EXCEPTION = e;
    }

    public ModuleCalendarDtoServicews() {
        super(__getWsdlLocation(), MODULECALENDARDTOSERVICEWS_QNAME);
    }

    public ModuleCalendarDtoServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODULECALENDARDTOSERVICEWS_QNAME, features);
    }

    public ModuleCalendarDtoServicews(URL wsdlLocation) {
        super(wsdlLocation, MODULECALENDARDTOSERVICEWS_QNAME);
    }

    public ModuleCalendarDtoServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODULECALENDARDTOSERVICEWS_QNAME, features);
    }

    public ModuleCalendarDtoServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModuleCalendarDtoServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModuleCalendarDtoServicewsEndpoint
     */
    @WebEndpoint(name = "ModuleCalendarDtoServicewsImplPort")
    public ModuleCalendarDtoServicewsEndpoint getModuleCalendarDtoServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "ModuleCalendarDtoServicewsImplPort"), ModuleCalendarDtoServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModuleCalendarDtoServicewsEndpoint
     */
    @WebEndpoint(name = "ModuleCalendarDtoServicewsImplPort")
    public ModuleCalendarDtoServicewsEndpoint getModuleCalendarDtoServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "ModuleCalendarDtoServicewsImplPort"), ModuleCalendarDtoServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODULECALENDARDTOSERVICEWS_EXCEPTION!= null) {
            throw MODULECALENDARDTOSERVICEWS_EXCEPTION;
        }
        return MODULECALENDARDTOSERVICEWS_WSDL_LOCATION;
    }

}
