
package org.sepro.parameterweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.parameterweb.serviceapi.ObjectFactoryPhoneFormat;
import org.sepro.parameterweb.serviceapi.PhoneFormatDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PhoneFormatServicewsEndpoint", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactoryPhoneFormat.class
})
public interface PhoneFormatServicewsEndpoint {


    /**
     * 
     * @param pageSize
     * @param page
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.PhoneFormatDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getPageAllPhoneFormatServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetPageAllPhoneFormatServicews")
    @ResponseWrapper(localName = "getPageAllPhoneFormatServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetPageAllPhoneFormatServicewsResponse")
    public List<PhoneFormatDto> getPageAllPhoneFormatServicews(
        @WebParam(name = "page", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int pageSize);

    /**
     * 
     * @param phoneFormatDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.PhoneFormatDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "createPhoneFormatServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreatePhoneFormatServicews")
    @ResponseWrapper(localName = "createPhoneFormatServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreatePhoneFormatServicewsResponse")
    public PhoneFormatDto createPhoneFormatServicews(
        @WebParam(name = "phoneFormatDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        PhoneFormatDto phoneFormatDto);

    /**
     * 
     * @param pageSize
     * @param page
     * @param phoneFormatDto
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.PhoneFormatDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchPagePhoneFormatServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchPagePhoneFormatServicews")
    @ResponseWrapper(localName = "searchPagePhoneFormatServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchPagePhoneFormatServicewsResponse")
    public List<PhoneFormatDto> searchPagePhoneFormatServicews(
        @WebParam(name = "phoneFormatDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        PhoneFormatDto phoneFormatDto,
        @WebParam(name = "page", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int pageSize);

    /**
     * 
     * @param phoneFormatDto
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.PhoneFormatDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchPhoneFormatServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchPhoneFormatServicews")
    @ResponseWrapper(localName = "searchPhoneFormatServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchPhoneFormatServicewsResponse")
    public List<PhoneFormatDto> searchPhoneFormatServicews(
        @WebParam(name = "phoneFormatDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        PhoneFormatDto phoneFormatDto);

    /**
     * 
     * @param phoneFormatDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.PhoneFormatDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "updatePhoneFormatServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdatePhoneFormatServicews")
    @ResponseWrapper(localName = "updatePhoneFormatServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdatePhoneFormatServicewsResponse")
    public PhoneFormatDto updatePhoneFormatServicews(
        @WebParam(name = "phoneFormatDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        PhoneFormatDto phoneFormatDto);

    /**
     * 
     * @param phoneFormatDto
     */
    @WebMethod
    @RequestWrapper(localName = "deletePhoneFormatServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeletePhoneFormatServicews")
    @ResponseWrapper(localName = "deletePhoneFormatServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeletePhoneFormatServicewsResponse")
    public void deletePhoneFormatServicews(
        @WebParam(name = "phoneFormatDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        PhoneFormatDto phoneFormatDto);

    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.PhoneFormatDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getAllPhoneFormatServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllPhoneFormatServicews")
    @ResponseWrapper(localName = "getAllPhoneFormatServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllPhoneFormatServicewsResponse")
    public List<PhoneFormatDto> getAllPhoneFormatServicews();

}
