
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PhoneFormatServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/PhoneFormatServicews/PhoneFormatServicewsImpl?wsdl")
public class PhoneFormatServicews
    extends Service
{

    private final static URL PHONEFORMATSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException PHONEFORMATSERVICEWS_EXCEPTION;
    private final static QName PHONEFORMATSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "PhoneFormatServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/PhoneFormatServicews/PhoneFormatServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PHONEFORMATSERVICEWS_WSDL_LOCATION = url;
        PHONEFORMATSERVICEWS_EXCEPTION = e;
    }

    public PhoneFormatServicews() {
        super(__getWsdlLocation(), PHONEFORMATSERVICEWS_QNAME);
    }

    public PhoneFormatServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), PHONEFORMATSERVICEWS_QNAME, features);
    }

    public PhoneFormatServicews(URL wsdlLocation) {
        super(wsdlLocation, PHONEFORMATSERVICEWS_QNAME);
    }

    public PhoneFormatServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PHONEFORMATSERVICEWS_QNAME, features);
    }

    public PhoneFormatServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhoneFormatServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PhoneFormatServicewsEndpoint
     */
    @WebEndpoint(name = "PhoneFormatServicewsImplPort")
    public PhoneFormatServicewsEndpoint getPhoneFormatServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "PhoneFormatServicewsImplPort"), PhoneFormatServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PhoneFormatServicewsEndpoint
     */
    @WebEndpoint(name = "PhoneFormatServicewsImplPort")
    public PhoneFormatServicewsEndpoint getPhoneFormatServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "PhoneFormatServicewsImplPort"), PhoneFormatServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PHONEFORMATSERVICEWS_EXCEPTION!= null) {
            throw PHONEFORMATSERVICEWS_EXCEPTION;
        }
        return PHONEFORMATSERVICEWS_WSDL_LOCATION;
    }

}
