
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PopuplistDtoServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/PopuplistDtoServicews/PopuplistDtoServicewsImpl?wsdl")
public class PopuplistDtoServicews
    extends Service
{

    private final static URL POPUPLISTDTOSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException POPUPLISTDTOSERVICEWS_EXCEPTION;
    private final static QName POPUPLISTDTOSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "PopuplistDtoServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/PopuplistDtoServicews/PopuplistDtoServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POPUPLISTDTOSERVICEWS_WSDL_LOCATION = url;
        POPUPLISTDTOSERVICEWS_EXCEPTION = e;
    }

    public PopuplistDtoServicews() {
        super(__getWsdlLocation(), POPUPLISTDTOSERVICEWS_QNAME);
    }

    public PopuplistDtoServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), POPUPLISTDTOSERVICEWS_QNAME, features);
    }

    public PopuplistDtoServicews(URL wsdlLocation) {
        super(wsdlLocation, POPUPLISTDTOSERVICEWS_QNAME);
    }

    public PopuplistDtoServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POPUPLISTDTOSERVICEWS_QNAME, features);
    }

    public PopuplistDtoServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PopuplistDtoServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PopuplistDtoServicewsEndpoint
     */
    @WebEndpoint(name = "PopuplistDtoServicewsImplPort")
    public PopuplistDtoServicewsEndpoint getPopuplistDtoServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "PopuplistDtoServicewsImplPort"), PopuplistDtoServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PopuplistDtoServicewsEndpoint
     */
    @WebEndpoint(name = "PopuplistDtoServicewsImplPort")
    public PopuplistDtoServicewsEndpoint getPopuplistDtoServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "PopuplistDtoServicewsImplPort"), PopuplistDtoServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POPUPLISTDTOSERVICEWS_EXCEPTION!= null) {
            throw POPUPLISTDTOSERVICEWS_EXCEPTION;
        }
        return POPUPLISTDTOSERVICEWS_WSDL_LOCATION;
    }

}
