
package org.sepro.parameterweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.parameterweb.serviceapi.ObjectFactoryPopuplist;
import org.sepro.parameterweb.serviceapi.PopuplistDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PopuplistDtoServicewsEndpoint", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactoryPopuplist.class
})
public interface PopuplistDtoServicewsEndpoint {


    /**
     * 
     * @param popuplistDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.PopuplistDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "updatePopuplistDtoServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdatePopuplistDtoServicews")
    @ResponseWrapper(localName = "updatePopuplistDtoServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdatePopuplistDtoServicewsResponse")
    public PopuplistDto updatePopuplistDtoServicews(
        @WebParam(name = "popuplistDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        PopuplistDto popuplistDto);

    /**
     * 
     * @param entite
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.PopuplistDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchPopuplistDtoServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchPopuplistDtoServicews")
    @ResponseWrapper(localName = "searchPopuplistDtoServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchPopuplistDtoServicewsResponse")
    public List<PopuplistDto> searchPopuplistDtoServicews(
        @WebParam(name = "entite", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        String entite);

    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.PopuplistDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getAllPopuplistDtoServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllPopuplistDtoServicews")
    @ResponseWrapper(localName = "getAllPopuplistDtoServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllPopuplistDtoServicewsResponse")
    public List<PopuplistDto> getAllPopuplistDtoServicews();

    /**
     * 
     * @param popuplistDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.PopuplistDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "createPopuplistDtoServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreatePopuplistDtoServicews")
    @ResponseWrapper(localName = "createPopuplistDtoServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreatePopuplistDtoServicewsResponse")
    public PopuplistDto createPopuplistDtoServicews(
        @WebParam(name = "popuplistDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        PopuplistDto popuplistDto);

    /**
     * 
     * @param popuplistDto
     */
    @WebMethod
    @RequestWrapper(localName = "deletePopuplistDtoServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeletePopuplistDtoServicews")
    @ResponseWrapper(localName = "deletePopuplistDtoServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeletePopuplistDtoServicewsResponse")
    public void deletePopuplistDtoServicews(
        @WebParam(name = "popuplistDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        PopuplistDto popuplistDto);

}
