
package org.sepro.parameterweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.parameterweb.serviceapi.ObjectFactoryProgramme;
import org.sepro.parameterweb.serviceapi.ProgrammeDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProgrammeDtoServicewsEndpoint", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactoryProgramme.class
})
public interface ProgrammeDtoServicewsEndpoint {


    /**
     * 
     * @param programmeDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteProgrammeServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteProgrammeServicews")
    @ResponseWrapper(localName = "deleteProgrammeServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteProgrammeServicewsResponse")
    public void deleteProgrammeServicews(
        @WebParam(name = "programmeDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ProgrammeDto programmeDto);

    /**
     * 
     * @param programmeDto
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.ProgrammeDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchProgrammeServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchProgrammeServicews")
    @ResponseWrapper(localName = "searchProgrammeServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchProgrammeServicewsResponse")
    public List<ProgrammeDto> searchProgrammeServicews(
        @WebParam(name = "programmeDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ProgrammeDto programmeDto);

    /**
     * 
     * @param programmeDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.ProgrammeDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "updateProgrammeServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateProgrammeServicews")
    @ResponseWrapper(localName = "updateProgrammeServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateProgrammeServicewsResponse")
    public ProgrammeDto updateProgrammeServicews(
        @WebParam(name = "programmeDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ProgrammeDto programmeDto);

    /**
     * 
     * @param programmeDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.ProgrammeDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "createProgrammeServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateProgrammeServicews")
    @ResponseWrapper(localName = "createProgrammeServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateProgrammeServicewsResponse")
    public ProgrammeDto createProgrammeServicews(
        @WebParam(name = "programmeDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ProgrammeDto programmeDto);

    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.ProgrammeDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getAllProgrammeServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllProgrammeServicews")
    @ResponseWrapper(localName = "getAllProgrammeServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllProgrammeServicewsResponse")
    public List<ProgrammeDto> getAllProgrammeServicews();

}
