
package org.sepro.parameterweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.parameterweb.serviceapi.ObjectFactoryProgrammeCalendar;
import org.sepro.parameterweb.serviceapi.ProgrammeCalendarDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProgrammeCalendarDtoServicewsEndpoint", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactoryProgrammeCalendar.class
})
public interface ProgrammeCalendarDtoServicewsEndpoint {


    /**
     * 
     * @param programmeCalendarDto
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.ProgrammeCalendarDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchProgrammeCalendarServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchProgrammeCalendarServicews")
    @ResponseWrapper(localName = "searchProgrammeCalendarServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchProgrammeCalendarServicewsResponse")
    public List<ProgrammeCalendarDto> searchProgrammeCalendarServicews(
        @WebParam(name = "programmeCalendarDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ProgrammeCalendarDto programmeCalendarDto);

    /**
     * 
     * @param programmeCalendarDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.ProgrammeCalendarDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "updateProgrammeCalendarServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateProgrammeCalendarServicews")
    @ResponseWrapper(localName = "updateProgrammeCalendarServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateProgrammeCalendarServicewsResponse")
    public ProgrammeCalendarDto updateProgrammeCalendarServicews(
        @WebParam(name = "programmeCalendarDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ProgrammeCalendarDto programmeCalendarDto);

    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.ProgrammeCalendarDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getAllProgrammeCalendarServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllProgrammeCalendarServicews")
    @ResponseWrapper(localName = "getAllProgrammeCalendarServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllProgrammeCalendarServicewsResponse")
    public List<ProgrammeCalendarDto> getAllProgrammeCalendarServicews();

    /**
     * 
     * @param programmeCalendarDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.ProgrammeCalendarDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "createProgrammeCalendarervicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateProgrammeCalendarervicews")
    @ResponseWrapper(localName = "createProgrammeCalendarervicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateProgrammeCalendarervicewsResponse")
    public ProgrammeCalendarDto createProgrammeCalendarervicews(
        @WebParam(name = "programmeCalendarDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ProgrammeCalendarDto programmeCalendarDto);

    /**
     * 
     * @param programmeCalendarDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteProgrammeCalendarServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteProgrammeCalendarServicews")
    @ResponseWrapper(localName = "deleteProgrammeCalendarServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteProgrammeCalendarServicewsResponse")
    public void deleteProgrammeCalendarServicews(
        @WebParam(name = "programmeCalendarDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ProgrammeCalendarDto programmeCalendarDto);

}
