
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProgrammeCalendarDtoServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ProgrammeCalendarDtoServicews/ProgrammeCalendarDtoServicewsImpl?wsdl")
public class ProgrammeCalendarDtoServicews
    extends Service
{

    private final static URL PROGRAMMECALENDARDTOSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException PROGRAMMECALENDARDTOSERVICEWS_EXCEPTION;
    private final static QName PROGRAMMECALENDARDTOSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "ProgrammeCalendarDtoServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ProgrammeCalendarDtoServicews/ProgrammeCalendarDtoServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROGRAMMECALENDARDTOSERVICEWS_WSDL_LOCATION = url;
        PROGRAMMECALENDARDTOSERVICEWS_EXCEPTION = e;
    }

    public ProgrammeCalendarDtoServicews() {
        super(__getWsdlLocation(), PROGRAMMECALENDARDTOSERVICEWS_QNAME);
    }

    public ProgrammeCalendarDtoServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROGRAMMECALENDARDTOSERVICEWS_QNAME, features);
    }

    public ProgrammeCalendarDtoServicews(URL wsdlLocation) {
        super(wsdlLocation, PROGRAMMECALENDARDTOSERVICEWS_QNAME);
    }

    public ProgrammeCalendarDtoServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROGRAMMECALENDARDTOSERVICEWS_QNAME, features);
    }

    public ProgrammeCalendarDtoServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProgrammeCalendarDtoServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProgrammeCalendarDtoServicewsEndpoint
     */
    @WebEndpoint(name = "ProgrammeCalendarDtoServicewsImplPort")
    public ProgrammeCalendarDtoServicewsEndpoint getProgrammeCalendarDtoServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "ProgrammeCalendarDtoServicewsImplPort"), ProgrammeCalendarDtoServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProgrammeCalendarDtoServicewsEndpoint
     */
    @WebEndpoint(name = "ProgrammeCalendarDtoServicewsImplPort")
    public ProgrammeCalendarDtoServicewsEndpoint getProgrammeCalendarDtoServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "ProgrammeCalendarDtoServicewsImplPort"), ProgrammeCalendarDtoServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROGRAMMECALENDARDTOSERVICEWS_EXCEPTION!= null) {
            throw PROGRAMMECALENDARDTOSERVICEWS_EXCEPTION;
        }
        return PROGRAMMECALENDARDTOSERVICEWS_WSDL_LOCATION;
    }

}
