
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProgrammeDtoServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ProgrammeDtoServicews/ProgrammeDtoServicewsImpl?wsdl")
public class ProgrammeDtoServicews
    extends Service
{

    private final static URL PROGRAMMEDTOSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException PROGRAMMEDTOSERVICEWS_EXCEPTION;
    private final static QName PROGRAMMEDTOSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "ProgrammeDtoServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ProgrammeDtoServicews/ProgrammeDtoServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROGRAMMEDTOSERVICEWS_WSDL_LOCATION = url;
        PROGRAMMEDTOSERVICEWS_EXCEPTION = e;
    }

    public ProgrammeDtoServicews() {
        super(__getWsdlLocation(), PROGRAMMEDTOSERVICEWS_QNAME);
    }

    public ProgrammeDtoServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROGRAMMEDTOSERVICEWS_QNAME, features);
    }

    public ProgrammeDtoServicews(URL wsdlLocation) {
        super(wsdlLocation, PROGRAMMEDTOSERVICEWS_QNAME);
    }

    public ProgrammeDtoServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROGRAMMEDTOSERVICEWS_QNAME, features);
    }

    public ProgrammeDtoServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProgrammeDtoServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProgrammeDtoServicewsEndpoint
     */
    @WebEndpoint(name = "ProgrammeDtoServicewsImplPort")
    public ProgrammeDtoServicewsEndpoint getProgrammeDtoServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "ProgrammeDtoServicewsImplPort"), ProgrammeDtoServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProgrammeDtoServicewsEndpoint
     */
    @WebEndpoint(name = "ProgrammeDtoServicewsImplPort")
    public ProgrammeDtoServicewsEndpoint getProgrammeDtoServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "ProgrammeDtoServicewsImplPort"), ProgrammeDtoServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROGRAMMEDTOSERVICEWS_EXCEPTION!= null) {
            throw PROGRAMMEDTOSERVICEWS_EXCEPTION;
        }
        return PROGRAMMEDTOSERVICEWS_WSDL_LOCATION;
    }

}
