
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegionServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/RegionServicews/RegionServicewsImpl?wsdl")
public class RegionServicews
    extends Service
{

    private final static URL REGIONSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException REGIONSERVICEWS_EXCEPTION;
    private final static QName REGIONSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "RegionServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/RegionServicews/RegionServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGIONSERVICEWS_WSDL_LOCATION = url;
        REGIONSERVICEWS_EXCEPTION = e;
    }

    public RegionServicews() {
        super(__getWsdlLocation(), REGIONSERVICEWS_QNAME);
    }

    public RegionServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGIONSERVICEWS_QNAME, features);
    }

    public RegionServicews(URL wsdlLocation) {
        super(wsdlLocation, REGIONSERVICEWS_QNAME);
    }

    public RegionServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGIONSERVICEWS_QNAME, features);
    }

    public RegionServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegionServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegionServicewsEndpoint
     */
    @WebEndpoint(name = "RegionServicewsImplPort")
    public RegionServicewsEndpoint getRegionServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "RegionServicewsImplPort"), RegionServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegionServicewsEndpoint
     */
    @WebEndpoint(name = "RegionServicewsImplPort")
    public RegionServicewsEndpoint getRegionServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "RegionServicewsImplPort"), RegionServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGIONSERVICEWS_EXCEPTION!= null) {
            throw REGIONSERVICEWS_EXCEPTION;
        }
        return REGIONSERVICEWS_WSDL_LOCATION;
    }

}
