
package org.sepro.parameterweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.parameterweb.serviceapi.ObjectFactoryRegion;
import org.sepro.parameterweb.serviceapi.RegionDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegionServicewsEndpoint", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactoryRegion.class
})
public interface RegionServicewsEndpoint {


    /**
     * 
     * @param pageSize
     * @param page
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.RegionDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getPageAllRegionServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetPageAllRegionServicews")
    @ResponseWrapper(localName = "getPageAllRegionServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetPageAllRegionServicewsResponse")
    public List<RegionDto> getPageAllRegionServicews(
        @WebParam(name = "page", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int pageSize);

    /**
     * 
     * @param regionDto
     * @param pageSize
     * @param page
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.RegionDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchPageRegionServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchPageRegionServicews")
    @ResponseWrapper(localName = "searchPageRegionServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchPageRegionServicewsResponse")
    public List<RegionDto> searchPageRegionServicews(
        @WebParam(name = "regionDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        RegionDto regionDto,
        @WebParam(name = "page", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int pageSize);

    /**
     * 
     * @param regionDto
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.RegionDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchRegionServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchRegionServicews")
    @ResponseWrapper(localName = "searchRegionServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchRegionServicewsResponse")
    public List<RegionDto> searchRegionServicews(
        @WebParam(name = "regionDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        RegionDto regionDto);

    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.RegionDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getAllRegionServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllRegionServicews")
    @ResponseWrapper(localName = "getAllRegionServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllRegionServicewsResponse")
    public List<RegionDto> getAllRegionServicews();

    /**
     * 
     * @param regionDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteRegionServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteRegionServicews")
    @ResponseWrapper(localName = "deleteRegionServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteRegionServicewsResponse")
    public void deleteRegionServicews(
        @WebParam(name = "regionDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        RegionDto regionDto);

    /**
     * 
     * @param regionDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.RegionDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "createRegionServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateRegionServicews")
    @ResponseWrapper(localName = "createRegionServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateRegionServicewsResponse")
    public RegionDto createRegionServicews(
        @WebParam(name = "regionDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        RegionDto regionDto);

    /**
     * 
     * @param regionDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.RegionDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "updateRegionServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateRegionServicews")
    @ResponseWrapper(localName = "updateRegionServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateRegionServicewsResponse")
    public RegionDto updateRegionServicews(
        @WebParam(name = "regionDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        RegionDto regionDto);

}
