
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RoomInventoryServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/RoomInventoryServicews/RoomInventoryServicewsImpl?wsdl")
public class RoomInventoryServicews
    extends Service
{

    private final static URL ROOMINVENTORYSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException ROOMINVENTORYSERVICEWS_EXCEPTION;
    private final static QName ROOMINVENTORYSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "RoomInventoryServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/RoomInventoryServicews/RoomInventoryServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROOMINVENTORYSERVICEWS_WSDL_LOCATION = url;
        ROOMINVENTORYSERVICEWS_EXCEPTION = e;
    }

    public RoomInventoryServicews() {
        super(__getWsdlLocation(), ROOMINVENTORYSERVICEWS_QNAME);
    }

    public RoomInventoryServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROOMINVENTORYSERVICEWS_QNAME, features);
    }

    public RoomInventoryServicews(URL wsdlLocation) {
        super(wsdlLocation, ROOMINVENTORYSERVICEWS_QNAME);
    }

    public RoomInventoryServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROOMINVENTORYSERVICEWS_QNAME, features);
    }

    public RoomInventoryServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoomInventoryServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RoomInventoryServicewsEndpoint
     */
    @WebEndpoint(name = "RoomInventoryServicewsImplPort")
    public RoomInventoryServicewsEndpoint getRoomInventoryServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "RoomInventoryServicewsImplPort"), RoomInventoryServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RoomInventoryServicewsEndpoint
     */
    @WebEndpoint(name = "RoomInventoryServicewsImplPort")
    public RoomInventoryServicewsEndpoint getRoomInventoryServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "RoomInventoryServicewsImplPort"), RoomInventoryServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROOMINVENTORYSERVICEWS_EXCEPTION!= null) {
            throw ROOMINVENTORYSERVICEWS_EXCEPTION;
        }
        return ROOMINVENTORYSERVICEWS_WSDL_LOCATION;
    }

}
