
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SessionDtoServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/SessionDtoServicews/SessionDtoServicewsImpl?wsdl")
public class SessionDtoServicews
    extends Service
{

    private final static URL SESSIONDTOSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException SESSIONDTOSERVICEWS_EXCEPTION;
    private final static QName SESSIONDTOSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "SessionDtoServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/SessionDtoServicews/SessionDtoServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SESSIONDTOSERVICEWS_WSDL_LOCATION = url;
        SESSIONDTOSERVICEWS_EXCEPTION = e;
    }

    public SessionDtoServicews() {
        super(__getWsdlLocation(), SESSIONDTOSERVICEWS_QNAME);
    }

    public SessionDtoServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), SESSIONDTOSERVICEWS_QNAME, features);
    }

    public SessionDtoServicews(URL wsdlLocation) {
        super(wsdlLocation, SESSIONDTOSERVICEWS_QNAME);
    }

    public SessionDtoServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SESSIONDTOSERVICEWS_QNAME, features);
    }

    public SessionDtoServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SessionDtoServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SessionDtoServicewsEndpoint
     */
    @WebEndpoint(name = "SessionDtoServicewsImplPort")
    public SessionDtoServicewsEndpoint getSessionDtoServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "SessionDtoServicewsImplPort"), SessionDtoServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SessionDtoServicewsEndpoint
     */
    @WebEndpoint(name = "SessionDtoServicewsImplPort")
    public SessionDtoServicewsEndpoint getSessionDtoServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "SessionDtoServicewsImplPort"), SessionDtoServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SESSIONDTOSERVICEWS_EXCEPTION!= null) {
            throw SESSIONDTOSERVICEWS_EXCEPTION;
        }
        return SESSIONDTOSERVICEWS_WSDL_LOCATION;
    }

}
