
package org.sepro.parameterweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.parameterweb.serviceapi.ObjectFactorySession;
import org.sepro.parameterweb.serviceapi.SessionDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SessionDtoServicewsEndpoint", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactorySession.class
})
public interface SessionDtoServicewsEndpoint {


    /**
     * 
     * @param sessionDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteSessionServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteSessionServicews")
    @ResponseWrapper(localName = "deleteSessionServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteSessionServicewsResponse")
    public void deleteSessionServicews(
        @WebParam(name = "sessionDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        SessionDto sessionDto);

    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.SessionDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getAllSessionServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllSessionServicews")
    @ResponseWrapper(localName = "getAllSessionServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllSessionServicewsResponse")
    public List<SessionDto> getAllSessionServicews();

    /**
     * 
     * @param sessionDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.SessionDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "createSessionServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateSessionServicews")
    @ResponseWrapper(localName = "createSessionServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateSessionServicewsResponse")
    public SessionDto createSessionServicews(
        @WebParam(name = "sessionDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        SessionDto sessionDto);

    /**
     * 
     * @param sessionDto
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.SessionDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchSessionServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchSessionServicews")
    @ResponseWrapper(localName = "searchSessionServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchSessionServicewsResponse")
    public List<SessionDto> searchSessionServicews(
        @WebParam(name = "sessionDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        SessionDto sessionDto);

    /**
     * 
     * @param sessionDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.SessionDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "updateSessionServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateSessionServicews")
    @ResponseWrapper(localName = "updateSessionServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateSessionServicewsResponse")
    public SessionDto updateSessionServicews(
        @WebParam(name = "sessionDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        SessionDto sessionDto);

}
