
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SubEstablishmentServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/SubEstablishmentServicews/SubEstablishmentServicewsImpl?wsdl")
public class SubEstablishmentServicews
    extends Service
{

    private final static URL SUBESTABLISHMENTSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException SUBESTABLISHMENTSERVICEWS_EXCEPTION;
    private final static QName SUBESTABLISHMENTSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "SubEstablishmentServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/SubEstablishmentServicews/SubEstablishmentServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUBESTABLISHMENTSERVICEWS_WSDL_LOCATION = url;
        SUBESTABLISHMENTSERVICEWS_EXCEPTION = e;
    }

    public SubEstablishmentServicews() {
        super(__getWsdlLocation(), SUBESTABLISHMENTSERVICEWS_QNAME);
    }

    public SubEstablishmentServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUBESTABLISHMENTSERVICEWS_QNAME, features);
    }

    public SubEstablishmentServicews(URL wsdlLocation) {
        super(wsdlLocation, SUBESTABLISHMENTSERVICEWS_QNAME);
    }

    public SubEstablishmentServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUBESTABLISHMENTSERVICEWS_QNAME, features);
    }

    public SubEstablishmentServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubEstablishmentServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SubEstablishmentServicewsEndpoint
     */
    @WebEndpoint(name = "SubEstablishmentServicewsImplPort")
    public SubEstablishmentServicewsEndpoint getSubEstablishmentServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "SubEstablishmentServicewsImplPort"), SubEstablishmentServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubEstablishmentServicewsEndpoint
     */
    @WebEndpoint(name = "SubEstablishmentServicewsImplPort")
    public SubEstablishmentServicewsEndpoint getSubEstablishmentServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "SubEstablishmentServicewsImplPort"), SubEstablishmentServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUBESTABLISHMENTSERVICEWS_EXCEPTION!= null) {
            throw SUBESTABLISHMENTSERVICEWS_EXCEPTION;
        }
        return SUBESTABLISHMENTSERVICEWS_WSDL_LOCATION;
    }

}
