
package org.sepro.parameterweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.parameterweb.serviceapi.ObjectFactorySubEstablishment;
import org.sepro.parameterweb.serviceapi.SubEstablishmentDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SubEstablishmentServicewsEndpoint", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
@XmlSeeAlso({
	ObjectFactorySubEstablishment.class
})
public interface SubEstablishmentServicewsEndpoint {


    /**
     * 
     * @param subestablishmentDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.SubEstablishmentDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "updateSubEstablishmentServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateSubEstablishmentServicews")
    @ResponseWrapper(localName = "updateSubEstablishmentServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateSubEstablishmentServicewsResponse")
    public SubEstablishmentDto updateSubEstablishmentServicews(
        @WebParam(name = "subestablishmentDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        SubEstablishmentDto subestablishmentDto);

    /**
     * 
     * @param subestablishmentDto
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.SubEstablishmentDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchSubEstablishmentServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchSubEstablishmentServicews")
    @ResponseWrapper(localName = "searchSubEstablishmentServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchSubEstablishmentServicewsResponse")
    public List<SubEstablishmentDto> searchSubEstablishmentServicews(
        @WebParam(name = "subestablishmentDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        SubEstablishmentDto subestablishmentDto);

    /**
     * 
     * @param subestablishmentDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteSubEstablishmentServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteSubEstablishmentServicews")
    @ResponseWrapper(localName = "deleteSubEstablishmentServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteSubEstablishmentServicewsResponse")
    public void deleteSubEstablishmentServicews(
        @WebParam(name = "subestablishmentDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        SubEstablishmentDto subestablishmentDto);

    /**
     * 
     * @param pageSize
     * @param page
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.SubEstablishmentDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getPageAllSubEstablishmentServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetPageAllSubEstablishmentServicews")
    @ResponseWrapper(localName = "getPageAllSubEstablishmentServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetPageAllSubEstablishmentServicewsResponse")
    public List<SubEstablishmentDto> getPageAllSubEstablishmentServicews(
        @WebParam(name = "page", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int pageSize);

    /**
     * 
     * @param subestablishmentDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.SubEstablishmentDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "createSubEstablishmentServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateSubEstablishmentServicews")
    @ResponseWrapper(localName = "createSubEstablishmentServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateSubEstablishmentServicewsResponse")
    public SubEstablishmentDto createSubEstablishmentServicews(
        @WebParam(name = "subestablishmentDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        SubEstablishmentDto subestablishmentDto);

    /**
     * 
     * @param subestablishmentDto
     * @param pageSize
     * @param page
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.SubEstablishmentDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchPageSubEstablishmentServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchPageSubEstablishmentServicews")
    @ResponseWrapper(localName = "searchPageSubEstablishmentServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchPageSubEstablishmentServicewsResponse")
    public List<SubEstablishmentDto> searchPageSubEstablishmentServicews(
        @WebParam(name = "subestablishmentDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        SubEstablishmentDto subestablishmentDto,
        @WebParam(name = "page", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int pageSize);

    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.SubEstablishmentDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getAllSubEstablishmentServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllSubEstablishmentServicews")
    @ResponseWrapper(localName = "getAllSubEstablishmentServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllSubEstablishmentServicewsResponse")
    public List<SubEstablishmentDto> getAllSubEstablishmentServicews();

}
