
package org.sepro.parameterweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TypeofClassServicews", targetNamespace = "http://serviceimpl.parameterweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/TypeofClassServicews/TypeofClassServicewsImpl?wsdl")
public class TypeofClassServicews
    extends Service
{

    private final static URL TYPEOFCLASSSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException TYPEOFCLASSSERVICEWS_EXCEPTION;
    private final static QName TYPEOFCLASSSERVICEWS_QNAME = new QName("http://serviceimpl.parameterweb.sepro.org/", "TypeofClassServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/TypeofClassServicews/TypeofClassServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TYPEOFCLASSSERVICEWS_WSDL_LOCATION = url;
        TYPEOFCLASSSERVICEWS_EXCEPTION = e;
    }

    public TypeofClassServicews() {
        super(__getWsdlLocation(), TYPEOFCLASSSERVICEWS_QNAME);
    }

    public TypeofClassServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), TYPEOFCLASSSERVICEWS_QNAME, features);
    }

    public TypeofClassServicews(URL wsdlLocation) {
        super(wsdlLocation, TYPEOFCLASSSERVICEWS_QNAME);
    }

    public TypeofClassServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TYPEOFCLASSSERVICEWS_QNAME, features);
    }

    public TypeofClassServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TypeofClassServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TypeofClassServicewsEndpoint
     */
    @WebEndpoint(name = "TypeofClassServicewsImplPort")
    public TypeofClassServicewsEndpoint getTypeofClassServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "TypeofClassServicewsImplPort"), TypeofClassServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TypeofClassServicewsEndpoint
     */
    @WebEndpoint(name = "TypeofClassServicewsImplPort")
    public TypeofClassServicewsEndpoint getTypeofClassServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.parameterweb.sepro.org/", "TypeofClassServicewsImplPort"), TypeofClassServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TYPEOFCLASSSERVICEWS_EXCEPTION!= null) {
            throw TYPEOFCLASSSERVICEWS_EXCEPTION;
        }
        return TYPEOFCLASSSERVICEWS_WSDL_LOCATION;
    }

}
