
package org.sepro.parameterweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.parameterweb.serviceapi.ObjectFactoryZipcode;
import org.sepro.parameterweb.serviceapi.ZipcodeDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZipServicewsEndpoint", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactoryZipcode.class
})
public interface ZipServicewsEndpoint {


    /**
     * 
     * @param zipcodeDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteZipcodeServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteZipcodeServicews")
    @ResponseWrapper(localName = "deleteZipcodeServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.DeleteZipcodeServicewsResponse")
    public void deleteZipcodeServicews(
        @WebParam(name = "zipcodeDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ZipcodeDto zipcodeDto);

    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.ZipcodeDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getAllZipcodeServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllZipcodeServicews")
    @ResponseWrapper(localName = "getAllZipcodeServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetAllZipcodeServicewsResponse")
    public List<ZipcodeDto> getAllZipcodeServicews();

    /**
     * 
     * @param pageSize
     * @param page
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.ZipcodeDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "getPageAllZipcodeServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetPageAllZipcodeServicews")
    @ResponseWrapper(localName = "getPageAllZipcodeServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.GetPageAllZipcodeServicewsResponse")
    public List<ZipcodeDto> getPageAllZipcodeServicews(
        @WebParam(name = "page", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int pageSize);

    /**
     * 
     * @param zipcodeDto
     * @param pageSize
     * @param page
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.ZipcodeDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchPageZipcodeServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchPageZipcodeServicews")
    @ResponseWrapper(localName = "searchPageZipcodeServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchPageZipcodeServicewsResponse")
    public List<ZipcodeDto> searchPageZipcodeServicews(
        @WebParam(name = "zipcodeDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ZipcodeDto zipcodeDto,
        @WebParam(name = "page", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        int pageSize);

    /**
     * 
     * @param zipcodeDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.ZipcodeDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "createZipcodeServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateZipcodeServicews")
    @ResponseWrapper(localName = "createZipcodeServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.CreateZipcodeServicewsResponse")
    public ZipcodeDto createZipcodeServicews(
        @WebParam(name = "zipcodeDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ZipcodeDto zipcodeDto);

    /**
     * 
     * @param zipcodeDto
     * @return
     *     returns org.sepro.parameterweb.serviceapi.ZipcodeDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "updateZipcodeServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateZipcodeServicews")
    @ResponseWrapper(localName = "updateZipcodeServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.UpdateZipcodeServicewsResponse")
    public ZipcodeDto updateZipcodeServicews(
        @WebParam(name = "zipcodeDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ZipcodeDto zipcodeDto);

    /**
     * 
     * @param zipcodeDto
     * @return
     *     returns java.util.List<org.sepro.parameterweb.serviceapi.ZipcodeDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
    @RequestWrapper(localName = "searchZipcodeServicews", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchZipcodeServicews")
    @ResponseWrapper(localName = "searchZipcodeServicewsResponse", targetNamespace = "http://serviceapi.parameterweb.sepro.org/", className = "org.sepro.parameterweb.serviceapi.SearchZipcodeServicewsResponse")
    public List<ZipcodeDto> searchZipcodeServicews(
        @WebParam(name = "zipcodeDto", targetNamespace = "http://serviceapi.parameterweb.sepro.org/")
        ZipcodeDto zipcodeDto);

}
