
package org.sepro.inscriptionweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InscriptionAuthServicews", targetNamespace = "http://serviceimpl.inscriptionweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/InscriptionAuthServicews/InscriptionAuthServicewsImpl?wsdl")
public class InscriptionAuthServicews
    extends Service
{

    private final static URL INSCRIPTIONAUTHSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException INSCRIPTIONAUTHSERVICEWS_EXCEPTION;
    private final static QName INSCRIPTIONAUTHSERVICEWS_QNAME = new QName("http://serviceimpl.inscriptionweb.sepro.org/", "InscriptionAuthServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/InscriptionAuthServicews/InscriptionAuthServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSCRIPTIONAUTHSERVICEWS_WSDL_LOCATION = url;
        INSCRIPTIONAUTHSERVICEWS_EXCEPTION = e;
    }

    public InscriptionAuthServicews() {
        super(__getWsdlLocation(), INSCRIPTIONAUTHSERVICEWS_QNAME);
    }

    public InscriptionAuthServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSCRIPTIONAUTHSERVICEWS_QNAME, features);
    }

    public InscriptionAuthServicews(URL wsdlLocation) {
        super(wsdlLocation, INSCRIPTIONAUTHSERVICEWS_QNAME);
    }

    public InscriptionAuthServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSCRIPTIONAUTHSERVICEWS_QNAME, features);
    }

    public InscriptionAuthServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InscriptionAuthServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InscriptionAuthServicewsEndpoint
     */
    @WebEndpoint(name = "InscriptionAuthServicewsImplPort")
    public InscriptionAuthServicewsEndpoint getInscriptionAuthServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.inscriptionweb.sepro.org/", "InscriptionAuthServicewsImplPort"), InscriptionAuthServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InscriptionAuthServicewsEndpoint
     */
    @WebEndpoint(name = "InscriptionAuthServicewsImplPort")
    public InscriptionAuthServicewsEndpoint getInscriptionAuthServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.inscriptionweb.sepro.org/", "InscriptionAuthServicewsImplPort"), InscriptionAuthServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSCRIPTIONAUTHSERVICEWS_EXCEPTION!= null) {
            throw INSCRIPTIONAUTHSERVICEWS_EXCEPTION;
        }
        return INSCRIPTIONAUTHSERVICEWS_WSDL_LOCATION;
    }

}
