
package org.sepro.inscriptionweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InscriptionSteptwoServicews", targetNamespace = "http://serviceimpl.inscriptionweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/InscriptionSteptwoServicews/InscriptionSteptwoServicewsImpl?wsdl")
public class InscriptionSteptwoServicews
    extends Service
{

    private final static URL INSCRIPTIONSTEPTWOSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException INSCRIPTIONSTEPTWOSERVICEWS_EXCEPTION;
    private final static QName INSCRIPTIONSTEPTWOSERVICEWS_QNAME = new QName("http://serviceimpl.inscriptionweb.sepro.org/", "InscriptionSteptwoServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/InscriptionSteptwoServicews/InscriptionSteptwoServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSCRIPTIONSTEPTWOSERVICEWS_WSDL_LOCATION = url;
        INSCRIPTIONSTEPTWOSERVICEWS_EXCEPTION = e;
    }

    public InscriptionSteptwoServicews() {
        super(__getWsdlLocation(), INSCRIPTIONSTEPTWOSERVICEWS_QNAME);
    }

    public InscriptionSteptwoServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSCRIPTIONSTEPTWOSERVICEWS_QNAME, features);
    }

    public InscriptionSteptwoServicews(URL wsdlLocation) {
        super(wsdlLocation, INSCRIPTIONSTEPTWOSERVICEWS_QNAME);
    }

    public InscriptionSteptwoServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSCRIPTIONSTEPTWOSERVICEWS_QNAME, features);
    }

    public InscriptionSteptwoServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InscriptionSteptwoServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InscriptionSteptwoServicewsEndpoint
     */
    @WebEndpoint(name = "InscriptionSteptwoServicewsImplPort")
    public InscriptionSteptwoServicewsEndpoint getInscriptionSteptwoServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.inscriptionweb.sepro.org/", "InscriptionSteptwoServicewsImplPort"), InscriptionSteptwoServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InscriptionSteptwoServicewsEndpoint
     */
    @WebEndpoint(name = "InscriptionSteptwoServicewsImplPort")
    public InscriptionSteptwoServicewsEndpoint getInscriptionSteptwoServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.inscriptionweb.sepro.org/", "InscriptionSteptwoServicewsImplPort"), InscriptionSteptwoServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSCRIPTIONSTEPTWOSERVICEWS_EXCEPTION!= null) {
            throw INSCRIPTIONSTEPTWOSERVICEWS_EXCEPTION;
        }
        return INSCRIPTIONSTEPTWOSERVICEWS_WSDL_LOCATION;
    }

}
