
package org.sepro.inscriptionweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.inscriptionweb.serviceapi.InscriptionStepfourDto;
import org.sepro.inscriptionweb.serviceapi.ObjectFactoryInscriptionStepfour;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InscriptionStepfourServicewsEndpoint", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
@XmlSeeAlso({
	org.sepro.inscriptionweb.serviceapi.ObjectFactoryInscriptionStepfour.class
})
public interface InscriptionStepfourServicewsEndpoint {


    /**
     * 
     * @param inscriptionStepfourDto
     * @return
     *     returns java.util.List<org.sepro.inscriptionweb.serviceapi.InscriptionStepfourDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
    @RequestWrapper(localName = "searchInscriptionStepfourServicews", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.SearchInscriptionStepfourServicews")
    @ResponseWrapper(localName = "searchInscriptionStepfourServicewsResponse", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.SearchInscriptionStepfourServicewsResponse")
    public List<InscriptionStepfourDto> searchInscriptionStepfourServicews(
        @WebParam(name = "inscriptionStepfourDto", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
        InscriptionStepfourDto inscriptionStepfourDto);

    /**
     * 
     * @param inscriptionStepfourDto
     * @return
     *     returns org.sepro.inscriptionweb.serviceapi.InscriptionStepfourDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
    @RequestWrapper(localName = "createInscriptionStepfourServicews", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.CreateInscriptionStepfourServicews")
    @ResponseWrapper(localName = "createInscriptionStepfourServicewsResponse", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.CreateInscriptionStepfourServicewsResponse")
    public InscriptionStepfourDto createInscriptionStepfourServicews(
        @WebParam(name = "inscriptionStepfourDto", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
        InscriptionStepfourDto inscriptionStepfourDto);

    /**
     * 
     * @param inscriptionStepfourDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteInscriptionStepfourServicews", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.DeleteInscriptionStepfourServicews")
    @ResponseWrapper(localName = "deleteInscriptionStepfourServicewsResponse", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.DeleteInscriptionStepfourServicewsResponse")
    public void deleteInscriptionStepfourServicews(
        @WebParam(name = "inscriptionStepfourDto", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
        InscriptionStepfourDto inscriptionStepfourDto);

    /**
     * 
     * @param inscriptionStepfourDto
     * @return
     *     returns org.sepro.inscriptionweb.serviceapi.InscriptionStepfourDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
    @RequestWrapper(localName = "updateInscriptionStepfourServicews", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.UpdateInscriptionStepfourServicews")
    @ResponseWrapper(localName = "updateInscriptionStepfourServicewsResponse", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.UpdateInscriptionStepfourServicewsResponse")
    public InscriptionStepfourDto updateInscriptionStepfourServicews(
        @WebParam(name = "inscriptionStepfourDto", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
        InscriptionStepfourDto inscriptionStepfourDto);

}
