
package org.sepro.inscriptionweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.inscriptionweb.serviceapi.InscriptionAuthentificationDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InscriptionAuthServicewsEndpoint", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.inscriptionweb.serviceapi.ObjectFactoryInscriptionAuth.class
})
public interface InscriptionAuthServicewsEndpoint {


    /**
     * 
     * @param inscriptionAuthentificationDto
     * @return
     *     returns java.util.List<org.sepro.inscriptionweb.serviceapi.InscriptionAuthentificationDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
    @RequestWrapper(localName = "searchInscriptionAuthServicews", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.SearchInscriptionAuthServicews")
    @ResponseWrapper(localName = "searchInscriptionAuthServicewsResponse", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.SearchInscriptionAuthServicewsResponse")
    public List<InscriptionAuthentificationDto> searchInscriptionAuthServicews(
        @WebParam(name = "inscriptionAuthentificationDto", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
        InscriptionAuthentificationDto inscriptionAuthentificationDto);

    /**
     * 
     * @param inscriptionAuthentificationDto
     * @return
     *     returns org.sepro.inscriptionweb.serviceapi.InscriptionAuthentificationDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
    @RequestWrapper(localName = "createInscriptionAuthServicews", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.CreateInscriptionAuthServicews")
    @ResponseWrapper(localName = "createInscriptionAuthServicewsResponse", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.CreateInscriptionAuthServicewsResponse")
    public InscriptionAuthentificationDto createInscriptionAuthServicews(
        @WebParam(name = "inscriptionAuthentificationDto", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
        InscriptionAuthentificationDto inscriptionAuthentificationDto);

    /**
     * 
     * @param inscriptionAuthentificationDto
     * @return
     *     returns org.sepro.inscriptionweb.serviceapi.InscriptionAuthentificationDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
    @RequestWrapper(localName = "updateInscriptionAuthServicews", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.UpdateInscriptionAuthServicews")
    @ResponseWrapper(localName = "updateInscriptionAuthServicewsResponse", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.UpdateInscriptionAuthServicewsResponse")
    public InscriptionAuthentificationDto updateInscriptionAuthServicews(
        @WebParam(name = "inscriptionAuthentificationDto", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
        InscriptionAuthentificationDto inscriptionAuthentificationDto);

    /**
     * 
     * @param inscriptionAuthentificationDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteInscriptionAuthServicews", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.DeleteInscriptionAuthServicews")
    @ResponseWrapper(localName = "deleteInscriptionAuthServicewsResponse", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.DeleteInscriptionAuthServicewsResponse")
    public void deleteInscriptionAuthServicews(
        @WebParam(name = "inscriptionAuthentificationDto", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
        InscriptionAuthentificationDto inscriptionAuthentificationDto);

}
