
package org.sepro.inscriptionweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InscriptionSteponeServicews", targetNamespace = "http://serviceimpl.inscriptionweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/InscriptionSteponeServicews/InscriptionSteponeServicewsImpl?wsdl")
public class InscriptionSteponeServicews
    extends Service
{

    private final static URL INSCRIPTIONSTEPONESERVICEWS_WSDL_LOCATION;
    private final static WebServiceException INSCRIPTIONSTEPONESERVICEWS_EXCEPTION;
    private final static QName INSCRIPTIONSTEPONESERVICEWS_QNAME = new QName("http://serviceimpl.inscriptionweb.sepro.org/", "InscriptionSteponeServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/InscriptionSteponeServicews/InscriptionSteponeServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSCRIPTIONSTEPONESERVICEWS_WSDL_LOCATION = url;
        INSCRIPTIONSTEPONESERVICEWS_EXCEPTION = e;
    }

    public InscriptionSteponeServicews() {
        super(__getWsdlLocation(), INSCRIPTIONSTEPONESERVICEWS_QNAME);
    }

    public InscriptionSteponeServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSCRIPTIONSTEPONESERVICEWS_QNAME, features);
    }

    public InscriptionSteponeServicews(URL wsdlLocation) {
        super(wsdlLocation, INSCRIPTIONSTEPONESERVICEWS_QNAME);
    }

    public InscriptionSteponeServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSCRIPTIONSTEPONESERVICEWS_QNAME, features);
    }

    public InscriptionSteponeServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InscriptionSteponeServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InscriptionSteponeServicewsEndpoint
     */
    @WebEndpoint(name = "InscriptionSteponeServicewsImplPort")
    public InscriptionSteponeServicewsEndpoint getInscriptionSteponeServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.inscriptionweb.sepro.org/", "InscriptionSteponeServicewsImplPort"), InscriptionSteponeServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InscriptionSteponeServicewsEndpoint
     */
    @WebEndpoint(name = "InscriptionSteponeServicewsImplPort")
    public InscriptionSteponeServicewsEndpoint getInscriptionSteponeServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.inscriptionweb.sepro.org/", "InscriptionSteponeServicewsImplPort"), InscriptionSteponeServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSCRIPTIONSTEPONESERVICEWS_EXCEPTION!= null) {
            throw INSCRIPTIONSTEPONESERVICEWS_EXCEPTION;
        }
        return INSCRIPTIONSTEPONESERVICEWS_WSDL_LOCATION;
    }

}
