
package org.sepro.inscriptionweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InscriptionStepfourServicews", targetNamespace = "http://serviceimpl.inscriptionweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/InscriptionStepfourServicews/InscriptionStepfourServicewsImpl?wsdl")
public class InscriptionStepfourServicews
    extends Service
{

    private final static URL INSCRIPTIONSTEPFOURSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException INSCRIPTIONSTEPFOURSERVICEWS_EXCEPTION;
    private final static QName INSCRIPTIONSTEPFOURSERVICEWS_QNAME = new QName("http://serviceimpl.inscriptionweb.sepro.org/", "InscriptionStepfourServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/InscriptionStepfourServicews/InscriptionStepfourServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSCRIPTIONSTEPFOURSERVICEWS_WSDL_LOCATION = url;
        INSCRIPTIONSTEPFOURSERVICEWS_EXCEPTION = e;
    }

    public InscriptionStepfourServicews() {
        super(__getWsdlLocation(), INSCRIPTIONSTEPFOURSERVICEWS_QNAME);
    }

    public InscriptionStepfourServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSCRIPTIONSTEPFOURSERVICEWS_QNAME, features);
    }

    public InscriptionStepfourServicews(URL wsdlLocation) {
        super(wsdlLocation, INSCRIPTIONSTEPFOURSERVICEWS_QNAME);
    }

    public InscriptionStepfourServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSCRIPTIONSTEPFOURSERVICEWS_QNAME, features);
    }

    public InscriptionStepfourServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InscriptionStepfourServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InscriptionStepfourServicewsEndpoint
     */
    @WebEndpoint(name = "InscriptionStepfourServicewsImplPort")
    public InscriptionStepfourServicewsEndpoint getInscriptionStepfourServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.inscriptionweb.sepro.org/", "InscriptionStepfourServicewsImplPort"), InscriptionStepfourServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InscriptionStepfourServicewsEndpoint
     */
    @WebEndpoint(name = "InscriptionStepfourServicewsImplPort")
    public InscriptionStepfourServicewsEndpoint getInscriptionStepfourServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.inscriptionweb.sepro.org/", "InscriptionStepfourServicewsImplPort"), InscriptionStepfourServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSCRIPTIONSTEPFOURSERVICEWS_EXCEPTION!= null) {
            throw INSCRIPTIONSTEPFOURSERVICEWS_EXCEPTION;
        }
        return INSCRIPTIONSTEPFOURSERVICEWS_WSDL_LOCATION;
    }

}
