
package org.sepro.inscriptionweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.inscriptionweb.serviceapi.InscriptionSteptreeDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InscriptionSteptreeServicewsEndpoint", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.inscriptionweb.serviceapi.ObjectFactoryInscriptionSteptree.class
})
public interface InscriptionSteptreeServicewsEndpoint {


    /**
     * 
     * @param inscriptionSteptreeDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteInscriptionSteptreeServicews", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.DeleteInscriptionSteptreeServicews")
    @ResponseWrapper(localName = "deleteInscriptionSteptreeServicewsResponse", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.DeleteInscriptionSteptreeServicewsResponse")
    public void deleteInscriptionSteptreeServicews(
        @WebParam(name = "inscriptionSteptreeDto", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
        InscriptionSteptreeDto inscriptionSteptreeDto);

    /**
     * 
     * @param inscriptionSteptreeDto
     * @return
     *     returns org.sepro.inscriptionweb.serviceapi.InscriptionSteptreeDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
    @RequestWrapper(localName = "createInscriptionSteptreeServicews", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.CreateInscriptionSteptreeServicews")
    @ResponseWrapper(localName = "createInscriptionSteptreeServicewsResponse", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.CreateInscriptionSteptreeServicewsResponse")
    public InscriptionSteptreeDto createInscriptionSteptreeServicews(
        @WebParam(name = "inscriptionSteptreeDto", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
        InscriptionSteptreeDto inscriptionSteptreeDto);

    /**
     * 
     * @param inscriptionSteptreeDto
     * @return
     *     returns java.util.List<org.sepro.inscriptionweb.serviceapi.InscriptionSteptreeDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
    @RequestWrapper(localName = "searchInscriptionSteptreeServicews", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.SearchInscriptionSteptreeServicews")
    @ResponseWrapper(localName = "searchInscriptionSteptreeServicewsResponse", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.SearchInscriptionSteptreeServicewsResponse")
    public List<InscriptionSteptreeDto> searchInscriptionSteptreeServicews(
        @WebParam(name = "inscriptionSteptreeDto", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
        InscriptionSteptreeDto inscriptionSteptreeDto);

    /**
     * 
     * @param inscriptionSteptreeDto
     * @return
     *     returns org.sepro.inscriptionweb.serviceapi.InscriptionSteptreeDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
    @RequestWrapper(localName = "updateInscriptionSteptreeServicews", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.UpdateInscriptionSteptreeServicews")
    @ResponseWrapper(localName = "updateInscriptionSteptreeServicewsResponse", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.UpdateInscriptionSteptreeServicewsResponse")
    public InscriptionSteptreeDto updateInscriptionSteptreeServicews(
        @WebParam(name = "inscriptionSteptreeDto", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
        InscriptionSteptreeDto inscriptionSteptreeDto);

}
