
package org.sepro.inscriptionweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.inscriptionweb.serviceapi.InscriptionSteptwoDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InscriptionSteptwoServicewsEndpoint", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.inscriptionweb.serviceapi.ObjectFactoryInscriptionSteptwo.class
})
public interface InscriptionSteptwoServicewsEndpoint {


    /**
     * 
     * @param inscriptionSteptwoDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteInscriptionSteptwoServicews", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.DeleteInscriptionSteptwoServicews")
    @ResponseWrapper(localName = "deleteInscriptionSteptwoServicewsResponse", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.DeleteInscriptionSteptwoServicewsResponse")
    public void deleteInscriptionSteptwoServicews(
        @WebParam(name = "inscriptionSteptwoDto", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
        InscriptionSteptwoDto inscriptionSteptwoDto);

    /**
     * 
     * @param inscriptionSteptwoDto
     * @return
     *     returns org.sepro.inscriptionweb.serviceapi.InscriptionSteptwoDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
    @RequestWrapper(localName = "createInscriptionSteptwoServicews", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.CreateInscriptionSteptwoServicews")
    @ResponseWrapper(localName = "createInscriptionSteptwoServicewsResponse", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.CreateInscriptionSteptwoServicewsResponse")
    public InscriptionSteptwoDto createInscriptionSteptwoServicews(
        @WebParam(name = "inscriptionSteptwoDto", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
        InscriptionSteptwoDto inscriptionSteptwoDto);

    /**
     * 
     * @param inscriptionSteptwoDto
     * @return
     *     returns org.sepro.inscriptionweb.serviceapi.InscriptionSteptwoDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
    @RequestWrapper(localName = "updateInscriptionSteptwoServicews", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.UpdateInscriptionSteptwoServicews")
    @ResponseWrapper(localName = "updateInscriptionSteptwoServicewsResponse", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.UpdateInscriptionSteptwoServicewsResponse")
    public InscriptionSteptwoDto updateInscriptionSteptwoServicews(
        @WebParam(name = "inscriptionSteptwoDto", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
        InscriptionSteptwoDto inscriptionSteptwoDto);

    /**
     * 
     * @param inscriptionSteptwoDto
     * @return
     *     returns java.util.List<org.sepro.inscriptionweb.serviceapi.InscriptionSteptwoDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
    @RequestWrapper(localName = "searchInscriptionSteptwoServicews", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.SearchInscriptionSteptwoServicews")
    @ResponseWrapper(localName = "searchInscriptionSteptwoServicewsResponse", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.SearchInscriptionSteptwoServicewsResponse")
    public List<InscriptionSteptwoDto> searchInscriptionSteptwoServicews(
        @WebParam(name = "inscriptionSteptwoDto", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
        InscriptionSteptwoDto inscriptionSteptwoDto);

}
