
package org.sepro.inscriptionweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.inscriptionweb.serviceapi.ProspectDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProspectServicewsEndpoint", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
@XmlSeeAlso({
    org.sepro.inscriptionweb.serviceapi.ObjectFactoryProspect.class
})
public interface ProspectServicewsEndpoint {


    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.inscriptionweb.serviceapi.ProspectDto>
     */
    @WebMethod(operationName = "SearchProspectServicews")
    @WebResult(targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/")
    @RequestWrapper(localName = "SearchProspectServicews", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.SearchProspectServicews")
    @ResponseWrapper(localName = "SearchProspectServicewsResponse", targetNamespace = "http://serviceapi.inscriptionweb.sepro.org/", className = "org.sepro.inscriptionweb.serviceapi.SearchProspectServicewsResponse")
    public List<ProspectDto> searchProspectServicews();

}
