
package org.sepro.inscriptionweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProspectServicews", targetNamespace = "http://serviceimpl.inscriptionweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ProspectServicews/ProspectServicewsImpl?wsdl")
public class ProspectServicews
    extends Service
{

    private final static URL PROSPECTSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException PROSPECTSERVICEWS_EXCEPTION;
    private final static QName PROSPECTSERVICEWS_QNAME = new QName("http://serviceimpl.inscriptionweb.sepro.org/", "ProspectServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ProspectServicews/ProspectServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROSPECTSERVICEWS_WSDL_LOCATION = url;
        PROSPECTSERVICEWS_EXCEPTION = e;
    }

    public ProspectServicews() {
        super(__getWsdlLocation(), PROSPECTSERVICEWS_QNAME);
    }

    public ProspectServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROSPECTSERVICEWS_QNAME, features);
    }

    public ProspectServicews(URL wsdlLocation) {
        super(wsdlLocation, PROSPECTSERVICEWS_QNAME);
    }

    public ProspectServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROSPECTSERVICEWS_QNAME, features);
    }

    public ProspectServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProspectServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProspectServicewsEndpoint
     */
    @WebEndpoint(name = "ProspectServicewsImplPort")
    public ProspectServicewsEndpoint getProspectServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.inscriptionweb.sepro.org/", "ProspectServicewsImplPort"), ProspectServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProspectServicewsEndpoint
     */
    @WebEndpoint(name = "ProspectServicewsImplPort")
    public ProspectServicewsEndpoint getProspectServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.inscriptionweb.sepro.org/", "ProspectServicewsImplPort"), ProspectServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROSPECTSERVICEWS_EXCEPTION!= null) {
            throw PROSPECTSERVICEWS_EXCEPTION;
        }
        return PROSPECTSERVICEWS_WSDL_LOCATION;
    }

}
