
package org.sepro.authentificationweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.authentificationweb.serviceapi.MenuDto;
import org.sepro.authentificationweb.serviceapi.ObjectFactoryMenu;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MenuServicewsEndpoint", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactoryMenu.class
})
public interface MenuServicewsEndpoint {


    /**
     * 
     * @param menuDto
     * @return
     *     returns org.sepro.authentificationweb.serviceapi.MenuDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "createMenuServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.CreateMenuServicews")
    @ResponseWrapper(localName = "createMenuServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.CreateMenuServicewsResponse")
    public MenuDto createMenuServicews(
        @WebParam(name = "menuDto", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        MenuDto menuDto);

    /**
     * 
     * @param menuDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteMenuServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.DeleteMenuServicews")
    @ResponseWrapper(localName = "deleteMenuServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.DeleteMenuServicewsResponse")
    public void deleteMenuServicews(
        @WebParam(name = "menuDto", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        MenuDto menuDto);

    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.authentificationweb.serviceapi.MenuDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "getAllMenuServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.GetAllMenuServicews")
    @ResponseWrapper(localName = "getAllMenuServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.GetAllMenuServicewsResponse")
    public List<MenuDto> getAllMenuServicews();

    /**
     * 
     * @param menuDto
     * @param pageSize
     * @param page
     * @return
     *     returns java.util.List<org.sepro.authentificationweb.serviceapi.MenuDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "searchPageMenuServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.SearchPageMenuServicews")
    @ResponseWrapper(localName = "searchPageMenuServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.SearchPageMenuServicewsResponse")
    public List<MenuDto> searchPageMenuServicews(
        @WebParam(name = "menuDto", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        MenuDto menuDto,
        @WebParam(name = "page", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        int pageSize);

    /**
     * 
     * @param pageSize
     * @param page
     * @return
     *     returns java.util.List<org.sepro.authentificationweb.serviceapi.MenuDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "getPageAllMenuServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.GetPageAllMenuServicews")
    @ResponseWrapper(localName = "getPageAllMenuServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.GetPageAllMenuServicewsResponse")
    public List<MenuDto> getPageAllMenuServicews(
        @WebParam(name = "page", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        int pageSize);

    /**
     * 
     * @param menuDto
     * @return
     *     returns org.sepro.authentificationweb.serviceapi.MenuDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "updateMenuServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.UpdateMenuServicews")
    @ResponseWrapper(localName = "updateMenuServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.UpdateMenuServicewsResponse")
    public MenuDto updateMenuServicews(
        @WebParam(name = "menuDto", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        MenuDto menuDto);

    /**
     * 
     * @param menuDto
     * @return
     *     returns java.util.List<org.sepro.authentificationweb.serviceapi.MenuDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "searchMenuServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.SearchMenuServicews")
    @ResponseWrapper(localName = "searchMenuServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.SearchMenuServicewsResponse")
    public List<MenuDto> searchMenuServicews(
        @WebParam(name = "menuDto", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        MenuDto menuDto);

}
