
package org.sepro.authentificationweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ModuleServicews", targetNamespace = "http://serviceimpl.authentificationweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ModuleServicews/ModuleServicewsImpl?wsdl")
public class ModuleServicews
    extends Service
{

    private final static URL MODULESERVICEWS_WSDL_LOCATION;
    private final static WebServiceException MODULESERVICEWS_EXCEPTION;
    private final static QName MODULESERVICEWS_QNAME = new QName("http://serviceimpl.authentificationweb.sepro.org/", "ModuleServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ModuleServicews/ModuleServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODULESERVICEWS_WSDL_LOCATION = url;
        MODULESERVICEWS_EXCEPTION = e;
    }

    public ModuleServicews() {
        super(__getWsdlLocation(), MODULESERVICEWS_QNAME);
    }

    public ModuleServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODULESERVICEWS_QNAME, features);
    }

    public ModuleServicews(URL wsdlLocation) {
        super(wsdlLocation, MODULESERVICEWS_QNAME);
    }

    public ModuleServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODULESERVICEWS_QNAME, features);
    }

    public ModuleServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModuleServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModuleServicewsEndpoint
     */
    @WebEndpoint(name = "ModuleServicewsImplPort")
    public ModuleServicewsEndpoint getModuleServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.authentificationweb.sepro.org/", "ModuleServicewsImplPort"), ModuleServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModuleServicewsEndpoint
     */
    @WebEndpoint(name = "ModuleServicewsImplPort")
    public ModuleServicewsEndpoint getModuleServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.authentificationweb.sepro.org/", "ModuleServicewsImplPort"), ModuleServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODULESERVICEWS_EXCEPTION!= null) {
            throw MODULESERVICEWS_EXCEPTION;
        }
        return MODULESERVICEWS_WSDL_LOCATION;
    }

}
