
package org.sepro.authentificationweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.authentificationweb.serviceapi.ModuleDto;
import org.sepro.authentificationweb.serviceapi.ObjectFactoryModule;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ModuleServicewsEndpoint", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactoryModule.class
})
public interface ModuleServicewsEndpoint {


    /**
     * 
     * @param moduleDto
     * @return
     *     returns org.sepro.authentificationweb.serviceapi.ModuleDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "updateModuleServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.UpdateModuleServicews")
    @ResponseWrapper(localName = "updateModuleServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.UpdateModuleServicewsResponse")
    public ModuleDto updateModuleServicews(
        @WebParam(name = "moduleDto", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        ModuleDto moduleDto);

    /**
     * 
     * @param moduleDto
     * @return
     *     returns org.sepro.authentificationweb.serviceapi.ModuleDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "createModuleServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.CreateModuleServicews")
    @ResponseWrapper(localName = "createModuleServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.CreateModuleServicewsResponse")
    public ModuleDto createModuleServicews(
        @WebParam(name = "moduleDto", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        ModuleDto moduleDto);

    /**
     * 
     * @param moduleDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteModuleServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.DeleteModuleServicews")
    @ResponseWrapper(localName = "deleteModuleServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.DeleteModuleServicewsResponse")
    public void deleteModuleServicews(
        @WebParam(name = "moduleDto", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        ModuleDto moduleDto);

    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.authentificationweb.serviceapi.ModuleDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "getAllModuleServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.GetAllModuleServicews")
    @ResponseWrapper(localName = "getAllModuleServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.GetAllModuleServicewsResponse")
    public List<ModuleDto> getAllModuleServicews();

    /**
     * 
     * @param moduleDto
     * @return
     *     returns java.util.List<org.sepro.authentificationweb.serviceapi.ModuleDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "searchModuleServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.SearchModuleServicews")
    @ResponseWrapper(localName = "searchModuleServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.SearchModuleServicewsResponse")
    public List<ModuleDto> searchModuleServicews(
        @WebParam(name = "moduleDto", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        ModuleDto moduleDto);

    /**
     * 
     * @param pageSize
     * @param page
     * @param moduleDto
     * @return
     *     returns java.util.List<org.sepro.authentificationweb.serviceapi.ModuleDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "searchPageModuleServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.SearchPageModuleServicews")
    @ResponseWrapper(localName = "searchPageModuleServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.SearchPageModuleServicewsResponse")
    public List<ModuleDto> searchPageModuleServicews(
        @WebParam(name = "moduleDto", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        ModuleDto moduleDto,
        @WebParam(name = "page", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        int pageSize);

    /**
     * 
     * @param pageSize
     * @param page
     * @return
     *     returns java.util.List<org.sepro.authentificationweb.serviceapi.ModuleDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "getPageAllModuleServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.GetPageAllModuleServicews")
    @ResponseWrapper(localName = "getPageAllModuleServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.GetPageAllModuleServicewsResponse")
    public List<ModuleDto> getPageAllModuleServicews(
        @WebParam(name = "page", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        int pageSize);

}
