
package org.sepro.authentificationweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProfileServicews", targetNamespace = "http://serviceimpl.authentificationweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ProfileServicews/ProfileServicewsImpl?wsdl")
public class ProfileServicews
    extends Service
{

    private final static URL PROFILESERVICEWS_WSDL_LOCATION;
    private final static WebServiceException PROFILESERVICEWS_EXCEPTION;
    private final static QName PROFILESERVICEWS_QNAME = new QName("http://serviceimpl.authentificationweb.sepro.org/", "ProfileServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/ProfileServicews/ProfileServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROFILESERVICEWS_WSDL_LOCATION = url;
        PROFILESERVICEWS_EXCEPTION = e;
    }

    public ProfileServicews() {
        super(__getWsdlLocation(), PROFILESERVICEWS_QNAME);
    }

    public ProfileServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROFILESERVICEWS_QNAME, features);
    }

    public ProfileServicews(URL wsdlLocation) {
        super(wsdlLocation, PROFILESERVICEWS_QNAME);
    }

    public ProfileServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROFILESERVICEWS_QNAME, features);
    }

    public ProfileServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProfileServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProfileServicewsEndpoint
     */
    @WebEndpoint(name = "ProfileServicewsImplPort")
    public ProfileServicewsEndpoint getProfileServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.authentificationweb.sepro.org/", "ProfileServicewsImplPort"), ProfileServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProfileServicewsEndpoint
     */
    @WebEndpoint(name = "ProfileServicewsImplPort")
    public ProfileServicewsEndpoint getProfileServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.authentificationweb.sepro.org/", "ProfileServicewsImplPort"), ProfileServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROFILESERVICEWS_EXCEPTION!= null) {
            throw PROFILESERVICEWS_EXCEPTION;
        }
        return PROFILESERVICEWS_WSDL_LOCATION;
    }

}
