
package org.sepro.authentificationweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RoleServicews", targetNamespace = "http://serviceimpl.authentificationweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/RoleServicews/RoleServicewsImpl?wsdl")
public class RoleServicews
    extends Service
{

    private final static URL ROLESERVICEWS_WSDL_LOCATION;
    private final static WebServiceException ROLESERVICEWS_EXCEPTION;
    private final static QName ROLESERVICEWS_QNAME = new QName("http://serviceimpl.authentificationweb.sepro.org/", "RoleServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/RoleServicews/RoleServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROLESERVICEWS_WSDL_LOCATION = url;
        ROLESERVICEWS_EXCEPTION = e;
    }

    public RoleServicews() {
        super(__getWsdlLocation(), ROLESERVICEWS_QNAME);
    }

    public RoleServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROLESERVICEWS_QNAME, features);
    }

    public RoleServicews(URL wsdlLocation) {
        super(wsdlLocation, ROLESERVICEWS_QNAME);
    }

    public RoleServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROLESERVICEWS_QNAME, features);
    }

    public RoleServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoleServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RoleServicewsEndpoint
     */
    @WebEndpoint(name = "RoleServicewsImplPort")
    public RoleServicewsEndpoint getRoleServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.authentificationweb.sepro.org/", "RoleServicewsImplPort"), RoleServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RoleServicewsEndpoint
     */
    @WebEndpoint(name = "RoleServicewsImplPort")
    public RoleServicewsEndpoint getRoleServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.authentificationweb.sepro.org/", "RoleServicewsImplPort"), RoleServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROLESERVICEWS_EXCEPTION!= null) {
            throw ROLESERVICEWS_EXCEPTION;
        }
        return ROLESERVICEWS_WSDL_LOCATION;
    }

}
