
package org.sepro.authentificationweb.serviceimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.sepro.authentificationweb.serviceapi.AuthDto;
import org.sepro.authentificationweb.serviceapi.ObjectFactoryUser;
import org.sepro.authentificationweb.serviceapi.UserDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserServicewsEndpoint", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
@XmlSeeAlso({
    ObjectFactoryUser.class
})
public interface UserServicewsEndpoint {


    /**
     * 
     * @param userlogin
     */
    @WebMethod
    @RequestWrapper(localName = "updateFailAttempts", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.UpdateFailAttempts")
    @ResponseWrapper(localName = "updateFailAttemptsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.UpdateFailAttemptsResponse")
    public void updateFailAttempts(
        @WebParam(name = "userlogin", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        String userlogin);

    /**
     * 
     * @param userlogin
     */
    @WebMethod
    @RequestWrapper(localName = "lockUser", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.LockUser")
    @ResponseWrapper(localName = "lockUserResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.LockUserResponse")
    public void lockUser(
        @WebParam(name = "userlogin", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        String userlogin);

    /**
     * 
     * @param pageSize
     * @param page
     * @param userDto
     * @return
     *     returns java.util.List<org.sepro.authentificationweb.serviceapi.UserDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "searchPageUserServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.SearchPageUserServicews")
    @ResponseWrapper(localName = "searchPageUserServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.SearchPageUserServicewsResponse")
    public List<UserDto> searchPageUserServicews(
        @WebParam(name = "userDto", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        UserDto userDto,
        @WebParam(name = "page", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        int pageSize);

    /**
     * 
     * @param userlogin
     */
    @WebMethod
    @RequestWrapper(localName = "resetFailAttempts", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.ResetFailAttempts")
    @ResponseWrapper(localName = "resetFailAttemptsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.ResetFailAttemptsResponse")
    public void resetFailAttempts(
        @WebParam(name = "userlogin", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        String userlogin);

    /**
     * 
     * @param authDto
     * @return
     *     returns org.sepro.authentificationweb.serviceapi.AuthDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "authentifyUserbyPasswordws", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.AuthentifyUserbyPasswordws")
    @ResponseWrapper(localName = "authentifyUserbyPasswordwsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.AuthentifyUserbyPasswordwsResponse")
    public AuthDto authentifyUserbyPasswordws(
        @WebParam(name = "authDto", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        AuthDto authDto);

    /**
     * 
     * @param userlogin
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "getUserAttempts", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.GetUserAttempts")
    @ResponseWrapper(localName = "getUserAttemptsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.GetUserAttemptsResponse")
    public int getUserAttempts(
        @WebParam(name = "userlogin", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        String userlogin);

    /**
     * 
     * @param userDto
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUserServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.DeleteUserServicews")
    @ResponseWrapper(localName = "deleteUserServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.DeleteUserServicewsResponse")
    public void deleteUserServicews(
        @WebParam(name = "userDto", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        UserDto userDto);

    /**
     * 
     * @return
     *     returns java.util.List<org.sepro.authentificationweb.serviceapi.UserDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "getAllUserServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.GetAllUserServicews")
    @ResponseWrapper(localName = "getAllUserServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.GetAllUserServicewsResponse")
    public List<UserDto> getAllUserServicews();

    /**
     * 
     * @param userDto
     * @return
     *     returns java.util.List<org.sepro.authentificationweb.serviceapi.UserDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "searchUserServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.SearchUserServicews")
    @ResponseWrapper(localName = "searchUserServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.SearchUserServicewsResponse")
    public List<UserDto> searchUserServicews(
        @WebParam(name = "userDto", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        UserDto userDto);

    /**
     * 
     * @param userDto
     * @return
     *     returns org.sepro.authentificationweb.serviceapi.UserDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "createUserServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.CreateUserServicews")
    @ResponseWrapper(localName = "createUserServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.CreateUserServicewsResponse")
    public UserDto createUserServicews(
        @WebParam(name = "userDto", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        UserDto userDto);

    /**
     * 
     * @param userDto
     * @return
     *     returns org.sepro.authentificationweb.serviceapi.UserDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "updateUserServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.UpdateUserServicews")
    @ResponseWrapper(localName = "updateUserServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.UpdateUserServicewsResponse")
    public UserDto updateUserServicews(
        @WebParam(name = "userDto", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        UserDto userDto);

    /**
     * 
     * @param userlogin
     * @return
     *     returns org.sepro.authentificationweb.serviceapi.UserDto
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "getUserBylogin", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.GetUserBylogin")
    @ResponseWrapper(localName = "getUserByloginResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.GetUserByloginResponse")
    public UserDto getUserBylogin(
        @WebParam(name = "userlogin", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        String userlogin);

    /**
     * 
     * @param pageSize
     * @param page
     * @return
     *     returns java.util.List<org.sepro.authentificationweb.serviceapi.UserDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
    @RequestWrapper(localName = "getPageAllUserServicews", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.GetPageAllUserServicews")
    @ResponseWrapper(localName = "getPageAllUserServicewsResponse", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/", className = "org.sepro.authentificationweb.serviceapi.GetPageAllUserServicewsResponse")
    public List<UserDto> getPageAllUserServicews(
        @WebParam(name = "page", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        int page,
        @WebParam(name = "pageSize", targetNamespace = "http://serviceapi.authentificationweb.sepro.org/")
        int pageSize);

}
