
package org.sepro.authentificationweb.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserServicews", targetNamespace = "http://serviceimpl.authentificationweb.sepro.org/", wsdlLocation = "http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/UserServicews/UserServicewsImpl?wsdl")
public class UserServicews
    extends Service
{

    private final static URL USERSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException USERSERVICEWS_EXCEPTION;
    private final static QName USERSERVICEWS_QNAME = new QName("http://serviceimpl.authentificationweb.sepro.org/", "UserServicews");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/org.sepro.web-1.0-SNAPSHOT/UserServicews/UserServicewsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERSERVICEWS_WSDL_LOCATION = url;
        USERSERVICEWS_EXCEPTION = e;
    }

    public UserServicews() {
        super(__getWsdlLocation(), USERSERVICEWS_QNAME);
    }

    public UserServicews(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERSERVICEWS_QNAME, features);
    }

    public UserServicews(URL wsdlLocation) {
        super(wsdlLocation, USERSERVICEWS_QNAME);
    }

    public UserServicews(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERSERVICEWS_QNAME, features);
    }

    public UserServicews(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserServicews(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserServicewsEndpoint
     */
    @WebEndpoint(name = "UserServicewsImplPort")
    public UserServicewsEndpoint getUserServicewsImplPort() {
        return super.getPort(new QName("http://serviceimpl.authentificationweb.sepro.org/", "UserServicewsImplPort"), UserServicewsEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserServicewsEndpoint
     */
    @WebEndpoint(name = "UserServicewsImplPort")
    public UserServicewsEndpoint getUserServicewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.authentificationweb.sepro.org/", "UserServicewsImplPort"), UserServicewsEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERSERVICEWS_EXCEPTION!= null) {
            throw USERSERVICEWS_EXCEPTION;
        }
        return USERSERVICEWS_WSDL_LOCATION;
    }

}
